<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20160714225308.1"><vh>@settings</vh>
<v t="amd.20160714225308.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20160714225308.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="leo.20180702145534.1" a="E"><vh>wsgi start/stop</vh>
<v t="leo.20180702142719.1"><vh>@button start wsgi</vh></v>
<v t="leo.20180702142849.1"><vh>@button stop wsgi</vh></v>
</v>
<v t="leo.20180702145555.1" a="E"><vh>http start/stop</vh>
<v t="leo.20180702145442.1"><vh>@button start http.server</vh></v>
<v t="leo.20180702145458.1"><vh>@button stop http.server</vh></v>
</v>
<v t="leo.20180703102027.1"><vh>@edit README.md</vh></v>
<v t="amd.20160714225245.2" a="E"><vh>about cmsimfly</vh>
<v t="amd.20160714230137.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20160714230155.1"><vh>@edit LICENSE</vh></v>
</v>
<v t="leo.20180701102750.1"><vh>@edit index.html</vh></v>
<v t="amd.20160714225914.1"><vh>@edit setup.py</vh></v>
<v t="amd.20160714230021.1"><vh>@edit init.py</vh></v>
<v t="amd.20160714230050.1"><vh>@edit nocache.py</vh></v>
<v t="leo.20180625155248.1"><vh>@edit pybean.py</vh></v>
<v t="leo.20180625155728.1"><vh>@edit schema.sql</vh></v>
<v t="amd.20160718130611.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20160717222221.1"><vh>@path static</vh>
<v t="leo.20180718091411.1"><vh>@edit cmsimply.css</vh></v>
<v t="amd.20160717222242.1"><vh>@edit axuploader.js</vh></v>
<v t="amd.20160718125932.1"><vh>@edit viewstl.html</vh></v>
<v t="amd.20160718125943.1"><vh>@edit stlviewer.js</vh></v>
<v t="amd.20160718212341.1"><vh>@edit jsc3d.js</vh></v>
</v>
<v t="amd.20160714230058.1" a="E"><vh>@clean wsgi.py</vh>
<v t="amd.20160714230122.1"><vh>wsgi declarations</vh></v>
</v>
<v t="amd.20160714230833.1" a="E"><vh>編輯 flaskapp.py</vh>
<v t="leo.20181104192450.1" a="E"><vh>@clean flaskapp.py</vh>
<v t="leo.20181104192502.1"><vh>Declarations </vh></v>
<v t="leo.20181104192502.2"><vh>checkLogin </vh></v>
<v t="leo.20181104192502.3"><vh>delete_file </vh></v>
<v t="leo.20181104192502.4"><vh>doDelete </vh></v>
<v t="leo.20181104192502.5"><vh>doSearch </vh></v>
<v t="leo.20181104192502.6"><vh>download </vh></v>
<v t="leo.20181104192502.7"><vh>download_list </vh></v>
<v t="leo.20181104192502.8"><vh>downloadlist_access_list </vh></v>
<v t="leo.20181104192502.9"><vh>downloads </vh></v>
<v t="leo.20181104192502.10"><vh>downloadselect_access_list </vh></v>
<v t="leo.20181104192502.11"><vh>edit_config </vh></v>
<v t="leo.20181104192502.12"><vh>edit_page </vh></v>
<v t="leo.20181104192502.13"><vh>editorfoot </vh></v>
<v t="leo.20181104192502.14"><vh>editorhead </vh></v>
<v t="leo.20181104192502.15"><vh>error_log </vh></v>
<v t="leo.20181104192502.16"><vh>file_get_contents </vh></v>
<v t="leo.20181104192502.17"><vh>file_lister </vh></v>
<v t="leo.20181104192502.18"><vh>file_selector </vh></v>
<v t="leo.20181104192502.19"><vh>file_selector_script </vh></v>
<v t="leo.20181104192502.20"><vh>fileaxupload </vh></v>
<v t="leo.20181104192502.21"><vh>fileuploadform </vh></v>
<v t="leo.20181104192502.22"><vh>flvplayer </vh></v>
<v t="leo.20181104192502.23"><vh>generate_pages </vh></v>
<v t="leo.20181104192502.24"><vh>get_page </vh></v>
<v t="leo.20181104192502.25"><vh>get_page2 </vh></v>
<v t="leo.20181104192502.26"><vh>image_delete_file </vh></v>
<v t="leo.20181104192502.27"><vh>image_doDelete </vh></v>
<v t="leo.20181104192502.28"><vh>image_list </vh></v>
<v t="leo.20181104192502.29"><vh>imageaxupload </vh></v>
<v t="leo.20181104192502.30"><vh>imagelist_access_list </vh></v>
<v t="leo.20181104192502.31"><vh>imageselect_access_list </vh></v>
<v t="leo.20181104192502.32"><vh>imageuploadform </vh></v>
<v t="leo.20181104192502.33"><vh>index </vh></v>
<v t="leo.20181104192502.34"><vh>isAdmin </vh></v>
<v t="leo.20181104192502.35"><vh>listdir </vh></v>
<v t="leo.20181104192502.36"><vh>load_list </vh></v>
<v t="leo.20181104192502.37"><vh>loadlist_access_list </vh></v>
<v t="leo.20181104192502.38"><vh>login </vh></v>
<v t="leo.20181104192502.39"><vh>logout </vh></v>
<v t="leo.20181104192502.40"><vh>parse_config </vh></v>
<v t="leo.20181104192502.41"><vh>_remove_h123_attrs </vh></v>
<v t="leo.20181104192502.42"><vh>parse_content </vh></v>
<v t="leo.20181104192502.43"><vh>render_menu </vh></v>
<v t="leo.20181104192502.44"><vh>render_menu2 </vh></v>
<v t="leo.20181104192502.45"><vh>saveConfig </vh></v>
<v t="leo.20181104192502.46"><vh>savePage </vh></v>
<v t="leo.20181104192502.47"><vh>search_content </vh></v>
<v t="leo.20181104192502.48"><vh>search_form </vh></v>
<v t="leo.20181104192502.49"><vh>send_file </vh></v>
<v t="leo.20181104192502.50"><vh>send_images </vh></v>
<v t="leo.20181104192502.51"><vh>send_static </vh></v>
<v t="leo.20181104192502.52"><vh>set_admin_css </vh></v>
<v t="leo.20181104192502.53"><vh>set_css </vh></v>
<v t="leo.20181104192502.54"><vh>set_css2 </vh></v>
<v t="leo.20181104192502.55"><vh>set_footer </vh></v>
<v t="leo.20181104192502.56"><vh>sitemap </vh></v>
<v t="leo.20181104192502.57"><vh>sitemap2 </vh></v>
<v t="leo.20181104192502.58"><vh>sizeof_fmt </vh></v>
<v t="leo.20181104192502.59"><vh>ssavePage </vh></v>
<v t="leo.20181104192502.60"><vh>syntaxhighlight </vh></v>
<v t="leo.20181104192502.61"><vh>syntaxhighlight2 </vh></v>
<v t="leo.20181104192502.62"><vh>tinymce_editor </vh></v>
<v t="leo.20181104192502.63"><vh>unique </vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20160714225245.2">we are going to use flask to write an simple cms system based upon cmsimply.

</t>
<t tx="amd.20160714225308.1"></t>
<t tx="amd.20160714225308.2">QSplitter::handle {
    background-color: #CAE1FF; /* lightSteelBlue1 */
}

QStackedWidget {
    /* background-color:lightpink; */
    border-color: red;
    padding: 0px;
    /* border-width: 0px; */
    /* background-color: yellow; */
}

QSplitter {
    border-color: white;
    background-color: white;
    border-style: solid;
}

QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 22px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 22px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 22px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 22px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 22px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 22px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20160714225308.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20160714230058.1">@language python
@tabwidth -4
@others
</t>
<t tx="amd.20160714230122.1">#!/usr/bin/python
# 導入同目錄下的 flaskapp.py
import flaskapp
import ssl

# 即使在近端仍希望以 https 模式下執行
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
context.load_cert_chain('localhost.crt', 'localhost.key')

# 取 flaskapp.py 中的 uwsgi 變數設定
uwsgi = flaskapp.uwsgi
if uwsgi:
    # 表示程式在雲端執行
    application = flaskapp.app
else:
    # 表示在近端執行, 以 python3 wsgi.py 執行
    flaskapp.app.run(
        host='127.0.0.1', port=8443, debug=True,
        ssl_context=context
    )
</t>
<t tx="amd.20160714230833.1"></t>
<t tx="amd.20160717222221.1"></t>
<t tx="leo.20180702142719.1">@language python
bpm = g.app.backgroundProcessManager
bpm.start_process(c, command='python wsgi.py', kind='wsgi', shell=True)


</t>
<t tx="leo.20180702142849.1">@language python
bpm = g.app.backgroundProcessManager
bpm.kill(kind="wsgi") 

</t>
<t tx="leo.20180702145442.1">@language python
bpm = g.app.backgroundProcessManager
bpm.start_process(c, command='python -m http.server', kind='http', shell=True)


</t>
<t tx="leo.20180702145458.1">@language python
bpm = g.app.backgroundProcessManager
bpm.kill(kind="http") 

</t>
<t tx="leo.20180702145534.1"></t>
<t tx="leo.20180702145555.1"></t>
<t tx="leo.20181104192450.1"># coding: utf-8
@others
if __name__ == "__main__":
    app.run()
@language python
@tabwidth -4
</t>
<t tx="leo.20181104192502.1">from flask import Flask, send_from_directory, request, redirect, \
    render_template, session, make_response, url_for, flash
import random
import math
import os
# init.py 為自行建立的起始物件
import init
# 利用 nocache.py 建立 @nocache decorator, 讓頁面不會留下 cache
from nocache import nocache
# the followings are for cmsimfly
import re
import os
import math
import hashlib
# use quote_plus() to generate URL
import urllib.parse
# use cgi.escape() to resemble php htmlspecialchars()
# use cgi.escape() or html.escape to generate data for textarea tag, otherwise Editor can not deal with some Javascript code.
import cgi
import sys
# for new parse_content function
#from bs4 import BeautifulSoup
# 為了使用 bs4.element, 改為 import bs4
import bs4
# for ssavePage and savePage
import shutil

# get the current directory of the file
_curdir = os.path.join(os.getcwd(), os.path.dirname(__file__))
sys.path.append(_curdir)

# 由 init.py 中的 uwsgi = False 或 True 決定在 uwsgi 模式或近端模式執行

#ends for cmsimfly

# 假如隨後要利用 blueprint 架構時, 可以將程式放在子目錄中
# 然後利用 register 方式導入
# 導入 g1 目錄下的 user1.py
#import users.g1.user1

# 確定程式檔案所在目錄, 在 Windows 有最後的反斜線
_curdir = os.path.join(os.getcwd(), os.path.dirname(__file__))
# 表示程式在近端執行, 最後必須決定是由 init.py 或此地決定目錄設定
config_dir = _curdir + "/config/"
static_dir = _curdir + "/static"
download_dir = _curdir + "/downloads/"
image_dir = _curdir + "/images/"

# 利用 init.py 啟動, 建立所需的相關檔案
initobj = init.Init()
# 取 init.py 中 Init 類別中的 class uwsgi 變數 (static variable) 設定
uwsgi = init.Init.uwsgi

# 必須先將 download_dir 設為 static_folder, 然後才可以用於 download 方法中的 app.static_folder 的呼叫
app = Flask(__name__)

# 設置隨後要在 blueprint 應用程式中引用的 global 變數
app.config['config_dir'] = config_dir
app.config['static_dir'] = static_dir
app.config['download_dir'] = download_dir

# 使用 session 必須要設定 secret_key
# In order to use sessions you have to set a secret key
# set the secret key.  keep this really secret:
app.secret_key = 'A0Zr9@8j/3yX R~XHH!jmN]LWX/,?R@T'

# 子目錄中註冊藍圖位置
#app.register_blueprint(users.g1.user1.g1app)


</t>
<t tx="leo.20181104192502.10">def downloadselect_access_list(files, starti, endi):
    """Accompanied with file_selector."""
    outstring = ""
    for index in range(int(starti)-1, int(endi)):
        fileName, fileExtension = os.path.splitext(files[index])
        fileSize = os.path.getsize(download_dir + "/" + files[index])
        outstring += '''&lt;input type="checkbox" name="filename" value="''' + \
                          files[index] + '''"&gt;&lt;a href="#" onclick='window.setLink("/downloads/''' + \
                          files[index] + '''",0); return false;'&gt;''' + files[index] + \
                          '''&lt;/a&gt; (''' + str(sizeof_fmt(fileSize)) + ''')&lt;br /&gt;'''
    return outstring


</t>
<t tx="leo.20181104192502.11">@app.route('/edit_config', defaults={'edit': 1})
@app.route('/edit_config/&lt;path:edit&gt;')
def edit_config(edit):
    """Config edit html form."""
    head, level, page = parse_content()
    directory = render_menu(head, level, page)
    if not isAdmin():
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                 directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Login&lt;/h1&gt;&lt;form method='post' action='checkLogin'&gt; \
                 Password:&lt;input type='password' name='password'&gt; \
                 &lt;input type='submit' value='login'&gt;&lt;/form&gt; \
                 &lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"
    else:
        site_title, password = parse_config()
        # edit config file
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                 directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Edit Config&lt;/h1&gt;&lt;form method='post' action='saveConfig'&gt; \
                 Site Title:&lt;input type='text' name='site_title' value='"+site_title+"' size='50'&gt;&lt;br /&gt; \
                 Password:&lt;input type='text' name='password' value='"+password+"' size='50'&gt;&lt;br /&gt; \
                 &lt;input type='hidden' name='password2' value='"+password+"'&gt; \
                 &lt;input type='submit' value='send'&gt;&lt;/form&gt; \
                 &lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"


# edit all page content
</t>
<t tx="leo.20181104192502.12">@app.route('/edit_page', defaults={'edit': 1})
@app.route('/edit_page/&lt;path:edit&gt;')
def edit_page(edit):
    """Page edit html form."""
    # check if administrator
    if not isAdmin():
        return redirect('/login')
    else:
        head, level, page = parse_content()
        directory = render_menu(head, level, page)
        pagedata =file_get_contents(config_dir + "content.htm")
        outstring = tinymce_editor(directory, cgi.escape(pagedata))
        return outstring


</t>
<t tx="leo.20181104192502.13">def editorfoot():
    return '''&lt;body&gt;'''


</t>
<t tx="leo.20181104192502.14">def editorhead():
    return '''
    &lt;br /&gt;
&lt;!--&lt;script src="//cdn.tinymce.com/4/tinymce.min.js"&gt;&lt;/script&gt;--&gt;
&lt;script src="/static/tinymce4/tinymce/tinymce.min.js"&gt;&lt;/script&gt;
&lt;script src="/static/tinymce4/tinymce/plugins/sh4tinymce/plugin.min.js"&gt;&lt;/script&gt;
&lt;link rel = "stylesheet" href = "/static/tinymce4/tinymce/plugins/sh4tinymce/style/style.css"&gt;
&lt;script&gt;
tinymce.init({
  selector: "textarea",
  height: 500,
  element_format : "html",
  language : "en",
  valid_elements : '*[*]',
  extended_valid_elements: "script[language|type|src]",
  plugins: [
    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
    'searchreplace wordcount visualblocks visualchars code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'emoticons template paste textcolor colorpicker textpattern imagetools sh4tinymce'
  ],
  toolbar1: 'insertfile save undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent',
  toolbar2: 'link image | print preview media | forecolor backcolor emoticons | code sh4tinymce',
  relative_urls: false,
  toolbar_items_size: 'small',
  file_picker_callback: function(callback, value, meta) {
        cmsFilePicker(callback, value, meta);
    },
  templates: [
    { title: 'Test template 1', content: 'Test 1' },
    { title: 'Test template 2', content: 'Test 2' }
  ],
  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tinymce.com/css/codepen.min.css'
  ]
});

function cmsFilePicker(callback, value, meta) {
    tinymce.activeEditor.windowManager.open({
        title: 'Uploaded File Browser',
        url: '/file_selector?type=' + meta.filetype,
        width: 800,
        height: 550,
    }, {
        oninsert: function (url, objVals) {
            callback(url, objVals);
        }
    });
};
&lt;/script&gt;
'''


</t>
<t tx="leo.20181104192502.15">@app.route('/error_log')
def error_log(self, info="Error"):
    head, level, page = parse_content()
    directory = render_menu(head, level, page)
    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
             directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;ERROR&lt;/h1&gt;" + info + "&lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.16">def file_get_contents(filename):
    # open file in utf-8 and return file content
    with open(filename, encoding="utf-8") as file:
        return file.read()


# 與 file_selector 配合, 用於 Tinymce4 編輯器的檔案選擇
</t>
<t tx="leo.20181104192502.17">def file_lister(directory, type=None, page=1, item_per_page=10):
    files = os.listdir(directory)
    total_rows = len(files)
    totalpage = math.ceil(total_rows/int(item_per_page))
    starti = int(item_per_page) * (int(page) - 1) + 1
    endi = starti + int(item_per_page) - 1
    outstring = file_selector_script()
    notlast = False
    if total_rows &gt; 0:
        outstring += "&lt;br /&gt;"
        if (int(page) * int(item_per_page)) &lt; total_rows:
            notlast = True
        if int(page) &gt; 1:
            outstring += "&lt;a href='"
            outstring += "file_selector?type=" + type + \
                              "&amp;amp;page=1&amp;amp;item_per_page=" + \
                              str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;&lt;&lt;&lt;/a&gt; "
            page_num = int(page) - 1
            outstring += "&lt;a href='"
            outstring += "file_selector?type=" + type + \
                              "&amp;amp;page=" + str(page_num) + \
                              "&amp;amp;item_per_page=" +str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;Previous&lt;/a&gt; "
        span = 10
        for index in range(int(page)-span, int(page)+span):
            if index&gt;= 0 and index&lt; totalpage:
                page_now = index + 1 
                if page_now == int(page):
                    outstring += "&lt;font size='+1' color='red'&gt;" + str(page) + " &lt;/font&gt;"
                else:
                    outstring += "&lt;a href='"
                    outstring += "file_selector?type=" + type + "&amp;amp;page=" + \
                                      str(page_now) + "&amp;amp;item_per_page=" + \
                                      str(item_per_page) + "&amp;amp;keyword=" + \
                                      str(session.get('download_keyword'))
                    outstring += "'&gt;" + str(page_now)+"&lt;/a&gt; "

        if notlast == True:
            nextpage = int(page) + 1
            outstring += " &lt;a href='"
            outstring += "file_selector?type=" + type + "&amp;amp;page=" + \
                               str(nextpage) + "&amp;amp;item_per_page=" + \
                               str(item_per_page) + "&amp;amp;keyword=" + \
                               str(session.get('download_keyword'))
            outstring += "'&gt;Next&lt;/a&gt;"
            outstring += " &lt;a href='"
            outstring += "file_selector?type=" + type + "&amp;amp;page=" + \
                               str(totalpage) + "&amp;amp;item_per_page=" + \
                               str(item_per_page) + "&amp;amp;keyword=" + \
                               str(session.get('download_keyword'))
            outstring += "'&gt;&gt;&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;"
        if (int(page) * int(item_per_page)) &lt; total_rows:
            notlast = True
            if type == "file":
                outstring += downloadselect_access_list(files, starti, endi) + "&lt;br /&gt;"
            else:
                outstring += imageselect_access_list(files, starti, endi) + "&lt;br /&gt;"
        else:
            outstring += "&lt;br /&gt;&lt;br /&gt;"
            if type == "file":
                outstring += downloadselect_access_list(files, starti, total_rows) + "&lt;br /&gt;"
            else:
                outstring += imageselect_access_list(files, starti, total_rows) + "&lt;br /&gt;"
        if int(page) &gt; 1:
            outstring += "&lt;a href='"
            outstring += "file_selector?type=" + type + \
                              "&amp;amp;page=1&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;&lt;&lt;&lt;/a&gt; "
            page_num = int(page) - 1
            outstring += "&lt;a href='"
            outstring += "file_selector?type=" + type + "&amp;amp;page=" + \
                               str(page_num) + "&amp;amp;item_per_page=" + \
                               str(item_per_page) + "&amp;amp;keyword=" + \
                               str(session.get('download_keyword'))
            outstring += "'&gt;Previous&lt;/a&gt;"
        span = 10
        for index in range(int(page)-span, int(page)+span):
            if index &gt;=0 and index &lt; totalpage:
                page_now = index + 1
                if page_now == int(page):
                    outstring += "&lt;font size='+1' color='red'&gt;"+str(page)+" &lt;/font&gt;"
                else:
                    outstring += "&lt;a href='"
                    outstring += "file_selector?type=" + type + "&amp;amp;page=" + \
                                       str(page_now) + "&amp;amp;item_per_page=" + \
                                       str(item_per_page) + "&amp;amp;keyword=" + \
                                       str(session.get('download_keyword'))
                    outstring += "'&gt;" + str(page_now) + "&lt;/a&gt; "
        if notlast == True:
            nextpage = int(page) + 1
            outstring += " &lt;a href='"
            outstring += "file_selector?type=" + type + "&amp;amp;page=" + \
                               str(nextpage) + "&amp;amp;item_per_page=" + \
                               str(item_per_page) + "&amp;amp;keyword=" + \
                               str(session.get('download_keyword'))
            outstring += "'&gt;Next&lt;/a&gt;"
            outstring += " &lt;a href='"
            outstring += "file_selector?type=" + type + "&amp;amp;page=" + \
                               str(totalpage) + "&amp;amp;item_per_page=" + \
                               str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;&gt;&gt;&lt;/a&gt;"
    else:
        outstring += "no data!"

    if type == "file":
        return outstring+"&lt;br /&gt;&lt;br /&gt;&lt;a href='fileuploadform'&gt;file upload&lt;/a&gt;"
    else:
        return outstring+"&lt;br /&gt;&lt;br /&gt;&lt;a href='imageuploadform'&gt;image upload&lt;/a&gt;"


# 配合 Tinymce4 讓使用者透過 html editor 引用所上傳的 files 與 images
</t>
<t tx="leo.20181104192502.18">@app.route('/file_selector', methods=['GET'])
def file_selector():
    if not isAdmin():
        return redirect("/login")
    else:
        if not request.args.get('type'):
            type= "file"
        else:
            type = request.args.get('type')
        if not request.args.get('page'):
            page = 1
        else:
            page = request.args.get('page')
        if not request.args.get('item_per_page'):
            item_per_page = 10
        else:
            item_per_page = request.args.get('item_per_page')
        if not request.args.get('keyword'):
            keyword = None
        else:
            keyword = request.args.get('keyword')

        if type == "file":

            return file_lister(download_dir, type, page, item_per_page)
        elif type == "image":
            return file_lister(image_dir, type, page, item_per_page)


</t>
<t tx="leo.20181104192502.19">def file_selector_script():
    return '''
&lt;script language="javascript" type="text/javascript"&gt;
$(function(){
    $('.a').on('click', function(event){
        setLink();
    });
});

function setLink (url, objVals) {
    top.tinymce.activeEditor.windowManager.getParams().oninsert(url, objVals);
    top.tinymce.activeEditor.windowManager.close();
    return false;
}
&lt;/script&gt;
'''


</t>
<t tx="leo.20181104192502.2">@app.route('/checkLogin', methods=['POST'])
def checkLogin():
    """Check user login process."""
    password = request.form["password"]
    site_title, saved_password = parse_config()
    hashed_password = hashlib.sha512(password.encode('utf-8')).hexdigest()
    if hashed_password == saved_password:
        session['admin'] = 1
        return redirect('/edit_page')
    return redirect('/')

 
</t>
<t tx="leo.20181104192502.20">@app.route('/fileaxupload', methods=['POST'])
# ajax jquery chunked file upload for flask
def fileaxupload():
    if isAdmin():
        # need to consider if the uploaded filename already existed.
        # right now all existed files will be replaced with the new files
        filename = request.args.get("ax-file-name")
        flag = request.args.get("start")
        if flag == "0":
            file = open(_curdir + "/downloads/" + filename, "wb")
        else:
            file = open(_curdir + "/downloads/" + filename, "ab")
        file.write(request.stream.read())
        file.close()
        return "files uploaded!"
    else:
        return redirect("/login")


</t>
<t tx="leo.20181104192502.21">@app.route('/fileuploadform', defaults={'edit':1})
@app.route('/fileuploadform/&lt;path:edit&gt;')
def fileuploadform(edit):
    if isAdmin():
        head, level, page = parse_content()
        directory = render_menu(head, level, page)
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;"+ \
                 directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;file upload&lt;/h1&gt;" + \
                 '''&lt;script src="/static/jquery.js" type="text/javascript"&gt;&lt;/script&gt;
&lt;script src="/static/axuploader.js" type="text/javascript"&gt;&lt;/script&gt;
&lt;script&gt;
$(document).ready(function(){
$('.prova').axuploader({url:'fileaxupload', allowExt:['jpg','png','gif','7z','pdf','zip','flv','stl','swf'],
finish:function(x,files)
    {
        alert('All files have been uploaded: '+files);
    },
enable:true,
remotePath:function(){
return 'downloads/';
}
});
});
&lt;/script&gt;
&lt;div class="prova"&gt;&lt;/div&gt;
&lt;input type="button" onclick="$('.prova').axuploader('disable')" value="asd" /&gt;
&lt;input type="button" onclick="$('.prova').axuploader('enable')" value="ok" /&gt;
&lt;/section&gt;&lt;/body&gt;&lt;/html&gt;
'''
    else:
        return redirect("/login")


</t>
<t tx="leo.20181104192502.22">@app.route('/flvplayer')
# 需要檢視能否取得 filepath 變數
def flvplayer(filepath=None):
    outstring = '''
&lt;object type="application/x-shockwave-flash" data="/static/player_flv_multi.swf" width="320" height="240"&gt;
     &lt;param name="movie" value="player_flv_multi.swf" /&gt;
     &lt;param name="allowFullScreen" value="true" /&gt;
     &lt;param name="FlashVars" value="flv=''' + filepath + '''&amp;amp;width=320&amp;amp;height=240&amp;amp;showstop=1&amp;amp;showvolume=1&amp;amp;showtime=1
     &amp;amp;startimage=/static/startimage_en.jpg&amp;amp;showfullscreen=1&amp;amp;bgcolor1=189ca8&amp;amp;bgcolor2=085c68
     &amp;amp;playercolor=085c68" /&gt;
&lt;/object&gt;
'''
    return outstring


</t>
<t tx="leo.20181104192502.23">@app.route('/generate_pages')
def generate_pages():
    # 必須決定如何處理重複標題頁面的轉檔
    import os
    # 確定程式檔案所在目錄, 在 Windows 有最後的反斜線
    _curdir = os.path.join(os.getcwd(), os.path.dirname(__file__))
    # 根據 content.htm 內容, 逐一產生各頁面檔案
    # 在此也要同時配合 render_menu2, 產生對應的 anchor 連結
    head, level, page = parse_content()
    # 處理重複標題 head 數列， 再重複標題按照次序加上 1, 2, 3...
    newhead = []
    for i, v in enumerate(head):
        # 各重複標題總數
        totalcount = head.count(v)
        # 目前重複標題出現總數
        count = head[:i].count(v)
        # 針對重複標題者, 附加目前重複標題出現數 +1, 未重複採原標題
        newhead.append(v + "-" + str(count + 1) if totalcount &gt; 1 else v)
    # 刪除 content 目錄中所有 html 檔案
    filelist = [ f for f in os.listdir(_curdir + "\\content\\") if f.endswith(".html") ]
    for f in filelist:
        os.remove(os.path.join(_curdir + "\\content\\", f))
    # 這裡需要建立專門寫出 html 的 write_page
    # index.html
    file = open(_curdir + "\\content\\index.html", "w", encoding="utf-8")
    file.write(get_page2(None, newhead, 0))
    file.close()
    # sitemap
    file = open(_curdir + "\\content\\sitemap.html", "w", encoding="utf-8")
    # sitemap2 需要 newhead
    file.write(sitemap2(newhead))
    file.close()
    # 以下轉檔, 改用 newhead 數列
    for i in range(len(newhead)):
        # 在此必須要將頁面中的 /images/ 字串換為 images/, /downloads/ 換為 downloads/
        # 因為 Flask 中靠 /images/ 取檔案, 但是一般 html 則採相對目錄取檔案
        # 此一字串置換在 get_page2 中進行
        file = open(_curdir + "\\content\\" + newhead[i] + ".html", "w", encoding="utf-8")
        # 增加以 newhead 作為輸入
        file.write(get_page2(newhead[i], newhead, 0))
        file.close()
    # generate each page html under content directory
    return "已經將網站轉為靜態網頁. &lt;a href='/'&gt;Home&lt;/a&gt;"
# seperate page need heading and edit variables, if edit=1, system will enter edit mode
# single page edit will use ssavePage to save content, it means seperate save page
</t>
<t tx="leo.20181104192502.24">@app.route('/get_page')
@app.route('/get_page/&lt;heading&gt;', defaults={'edit': 0})
@app.route('/get_page/&lt;heading&gt;/&lt;int:edit&gt;')
def get_page(heading, edit):
    head, level, page = parse_content()
    directory = render_menu(head, level, page)
    if heading is None:
        heading = head[0]
    # 因為同一 heading 可能有多頁, 因此不可使用 head.index(heading) 搜尋 page_order
    page_order_list, page_content_list = search_content(head, page, heading)
    return_content = ""
    pagedata = ""
    outstring = ""
    outstring_duplicate = ""
    pagedata_duplicate = ""
    outstring_list = []
    for i in range(len(page_order_list)):
        #page_order = head.index(heading)
        page_order = page_order_list[i]
        if page_order == 0:
            last_page = ""
        else:
            last_page = head[page_order-1] + " &lt;&lt; &lt;a href='/get_page/" + \
                             head[page_order-1] + "'&gt;Previous&lt;/a&gt;"
        if page_order == len(head) - 1:
            # no next page
            next_page = ""
        else:
            next_page = "&lt;a href='/get_page/"+ head[page_order+1] + \
                              "'&gt;Next&lt;/a&gt; &gt;&gt; " + head[page_order+1]
        if len(page_order_list) &gt; 1:
            return_content += last_page + " " + next_page + \
                                      "&lt;br /&gt;&lt;h1&gt;" + heading + "&lt;/h1&gt;" + \
                                      page_content_list[i] + "&lt;br /&gt;"+ \
                                      last_page + " " + next_page + "&lt;br /&gt;&lt;hr&gt;"
            pagedata_duplicate = "&lt;h"+level[page_order] + "&gt;" + heading + \
                                          "&lt;/h"+level[page_order] + "&gt;" + page_content_list[i]
            outstring_list.append(last_page + " " + next_page + "&lt;br /&gt;" + tinymce_editor(directory, cgi.escape(pagedata_duplicate), page_order))
        else:
            return_content += last_page + " " + next_page + "&lt;br /&gt;&lt;h1&gt;" +\
                                      heading + "&lt;/h1&gt;" + page_content_list[i] + "&lt;br /&gt;" + last_page + " " + next_page
            
        pagedata += "&lt;h"+level[page_order] + "&gt;" + heading + "&lt;/h" + level[page_order] + "&gt;" + page_content_list[i]
        # 利用 cgi.escape() 將 specialchar 轉成只能顯示的格式
        outstring += last_page + " " + next_page + "&lt;br /&gt;" + tinymce_editor(directory, cgi.escape(pagedata), page_order)
    
    # edit=0 for viewpage
    if edit == 0:
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                 directory + "&lt;/nav&gt;&lt;section&gt;" + return_content + "&lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"
    # enter edit mode
    else:
        # check if administrator
        if not isAdmin():
            redirect(url_for('login'))
        else:
            if len(page_order_list) &gt; 1:
                # 若碰到重複頁面頁印, 且要求編輯, 則導向 edit_page
                #return redirect("/edit_page")
                for i in range(len(page_order_list)):
                    outstring_duplicate += outstring_list[i] + "&lt;br /&gt;&lt;hr&gt;"
                return outstring_duplicate
            else:
            #pagedata = "&lt;h"+level[page_order]+"&gt;"+heading+"&lt;/h"+level[page_order]+"&gt;"+search_content(head, page, heading)
            #outstring = last_page+" "+next_page+"&lt;br /&gt;"+ tinymce_editor(directory, cgi.escape(pagedata), page_order)
                return outstring


# seperate page need heading and edit variables, if edit=1, system will enter edit mode
# single page edit will use ssavePage to save content, it means seperate save page
'''
@app.route('/get_page2')
@app.route('/get_page2/&lt;heading&gt;', defaults={'edit': 0})
@app.route('/get_page2/&lt;heading&gt;/&lt;int:edit&gt;')
'''
</t>
<t tx="leo.20181104192502.25">def get_page2(heading, head, edit):
    not_used_head, level, page = parse_content()
    # 直接在此將 /images/ 換為 ./../images/, /downloads/ 換為 ./../downloads/, 以 content 為基準的相對目錄設定
    page = [w.replace('/images/', './../images/') for w in page]
    page = [w.replace('/downloads/', './../downloads/') for w in page]
    directory = render_menu2(head, level, page)
    if heading is None:
        heading = head[0]
    # 因為同一 heading 可能有多頁, 因此不可使用 head.index(heading) 搜尋 page_order
    page_order_list, page_content_list = search_content(head, page, heading)
    return_content = ""
    pagedata = ""
    outstring = ""
    outstring_duplicate = ""
    pagedata_duplicate = ""
    outstring_list = []
    for i in range(len(page_order_list)):
        #page_order = head.index(heading)
        page_order = page_order_list[i]
        if page_order == 0:
            last_page = ""
        else:
            #last_page = head[page_order-1]+ " &lt;&lt; &lt;a href='/get_page/" + head[page_order-1] + "'&gt;Previous&lt;/a&gt;"
            last_page = head[page_order-1] + " &lt;&lt; &lt;a href='"+head[page_order-1] + ".html'&gt;Previous&lt;/a&gt;"
        if page_order == len(head) - 1:
            # no next page
            next_page = ""
        else:
            #next_page = "&lt;a href='/get_page/"+head[page_order+1] + "'&gt;Next&lt;/a&gt; &gt;&gt; " + head[page_order+1]
            next_page = "&lt;a href='" + head[page_order+1] + ".html'&gt;Next&lt;/a&gt; &gt;&gt; " + head[page_order+1]
        if len(page_order_list) &gt; 1:
            return_content += last_page + " " + next_page + "&lt;br /&gt;&lt;h1&gt;" + \
                                      heading + "&lt;/h1&gt;" + page_content_list[i] + \
                                      "&lt;br /&gt;" + last_page + " "+ next_page + "&lt;br /&gt;&lt;hr&gt;"
            pagedata_duplicate = "&lt;h"+level[page_order] + "&gt;" + heading + "&lt;/h" + level[page_order]+"&gt;"+page_content_list[i]
            outstring_list.append(last_page + " " + next_page + "&lt;br /&gt;" + tinymce_editor(directory, cgi.escape(pagedata_duplicate), page_order))
        else:
            return_content += last_page + " " + next_page + "&lt;br /&gt;&lt;h1&gt;" + \
                                      heading + "&lt;/h1&gt;" + page_content_list[i] + \
                                      "&lt;br /&gt;" + last_page + " " + next_page
            
        pagedata += "&lt;h" + level[page_order] + "&gt;" + heading + \
                          "&lt;/h" + level[page_order] + "&gt;" + page_content_list[i]
        # 利用 cgi.escape() 將 specialchar 轉成只能顯示的格式
        outstring += last_page + " " + next_page + "&lt;br /&gt;" + tinymce_editor(directory, cgi.escape(pagedata), page_order)
    
    # edit=0 for viewpage
    if edit == 0:
        return set_css2() + "&lt;div class='container'&gt;&lt;nav&gt;"+ \
        directory + "&lt;/nav&gt;&lt;section&gt;" + return_content + "&lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"
    # enter edit mode
    else:
        # check if administrator
        if not isAdmin():
            redirect(url_for('login'))
        else:
            if len(page_order_list) &gt; 1:
                # 若碰到重複頁面頁印, 且要求編輯, 則導向 edit_page
                #return redirect("/edit_page")
                for i in range(len(page_order_list)):
                    outstring_duplicate += outstring_list[i] + "&lt;br /&gt;&lt;hr&gt;"
                return outstring_duplicate
            else:
            #pagedata = "&lt;h" + level[page_order]+"&gt;" + heading + "&lt;/h" + level[page_order] + "&gt;" + search_content(head, page, heading)
            #outstring = last_page + " " + next_page + "&lt;br /&gt;" + tinymce_editor(directory, cgi.escape(pagedata), page_order)
                return outstring


</t>
<t tx="leo.20181104192502.26">@app.route('/image_delete_file', methods=['POST'])
def image_delete_file():
    if not isAdmin():
        return redirect("/login")
    filename = request.form['filename']
    head, level, page = parse_content()
    directory = render_menu(head, level, page)
    if filename is None:
        outstring = "no file selected!"
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                 directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Delete Error&lt;/h1&gt;" + \
                 outstring + "&lt;br/&gt;&lt;br /&gt;&lt;/body&gt;&lt;/html&gt;"
    outstring = "delete all these files?&lt;br /&gt;&lt;br /&gt;"
    outstring += "&lt;form method='post' action='image_doDelete'&gt;"
    # only one file is selected
    if isinstance(filename, str):
        outstring += filename + "&lt;input type='hidden' name='filename' value='" + \
                          filename + "'&gt;&lt;br /&gt;"
    else:
        # multiple files selected
        for index in range(len(filename)):
            outstring += filename[index] + "&lt;input type='hidden' name='filename' value='" + \
                              filename[index] + "'&gt;&lt;br /&gt;"
    outstring += "&lt;br /&gt;&lt;input type='submit' value='delete'&gt;&lt;/form&gt;"

    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
             directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Download List&lt;/h1&gt;" + \
             outstring + "&lt;br/&gt;&lt;br /&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.27">@app.route('/image_doDelete', methods=['POST'])
def image_doDelete():
    if not isAdmin():
        return redirect("/login")
    # delete files
    filename = request.form['filename']
    outstring = "all these files will be deleted:&lt;br /&gt;&lt;br /&gt;"
    # only select one file
    if isinstance(filename, str):
        try:
            os.remove(image_dir + "/" + filename)
            outstring += filename + " deleted!"
        except:
            outstring += filename + "Error, can not delete files!&lt;br /&gt;"
    else:
        # multiple files selected
        for index in range(len(filename)):
            try:
                os.remove(image_dir + "/" + filename[index])
                outstring += filename[index] + " deleted!&lt;br /&gt;"
            except:
                outstring += filename[index] + "Error, can not delete files!&lt;br /&gt;"

    head, level, page = parse_content()
    directory = render_menu(head, level, page)

    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
             directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Image List&lt;/h1&gt;" + \
             outstring + "&lt;br/&gt;&lt;br /&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.28">@app.route('/image_list', methods=['GET'])
def image_list():
    if not isAdmin():
        return redirect("/login")
    else:
        if not request.args.get('edit'):
            edit= 1
        else:
            edit = request.args.get('edit')
        if not request.args.get('page'):
            page = 1
        else:
            page = request.args.get('page')
        if not request.args.get('item_per_page'):
            item_per_page = 10
        else:
            item_per_page = request.args.get('item_per_page')
        if not request.args.get('keyword'):
            keyword = ""
        else:
            keyword = request.args.get('keyword')
            session['image_keyword'] = keyword
    files = os.listdir(image_dir)
    if keyword is not "":
        files = [elem for elem in files if str(keyword) in elem]
    files.sort()
    total_rows = len(files)
    totalpage = math.ceil(total_rows/int(item_per_page))
    starti = int(item_per_page) * (int(page) - 1) + 1
    endi = starti + int(item_per_page) - 1
    outstring = "&lt;form method='post' action='image_delete_file'&gt;"
    notlast = False
    if total_rows &gt; 0:
        outstring += "&lt;br /&gt;"
        if (int(page) * int(item_per_page)) &lt; total_rows:
            notlast = True
        if int(page) &gt; 1:
            outstring += "&lt;a href='"
            outstring += "image_list?&amp;amp;page=1&amp;amp;item_per_page=" + \
                              str(item_per_page) + "&amp;amp;keyword=" + str(session.get('image_keyword'))
            outstring += "'&gt;&lt;&lt;&lt;/a&gt; "
            page_num = int(page) - 1
            outstring += "&lt;a href='"
            outstring += "image_list?&amp;amp;page=" + str(page_num) + \
                              "&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('image_keyword'))
            outstring += "'&gt;Previous&lt;/a&gt; "
        span = 10
        for index in range(int(page)-span, int(page)+span):
            if index &gt;= 0 and index &lt; totalpage:
                page_now = index + 1 
                if page_now == int(page):
                    outstring += "&lt;font size='+1' color='red'&gt;" + str(page) + " &lt;/font&gt;"
                else:
                    outstring += "&lt;a href='"
                    outstring += "image_list?&amp;amp;page=" + str(page_now) + \
                                      "&amp;amp;item_per_page=" + str(item_per_page) + \
                                      "&amp;amp;keyword=" + str(session.get('image_keyword'))
                    outstring += "'&gt;" + str(page_now) + "&lt;/a&gt; "

        if notlast == True:
            nextpage = int(page) + 1
            outstring += " &lt;a href='"
            outstring += "image_list?&amp;amp;page=" + str(nextpage) + \
                              "&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('image_keyword'))
            outstring += "'&gt;Next&lt;/a&gt;"
            outstring += " &lt;a href='"
            outstring += "image_list?&amp;amp;page=" + str(totalpage) + \
                              "&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('image_keyword'))
            outstring += "'&gt;&gt;&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;"
        if (int(page) * int(item_per_page)) &lt; total_rows:
            notlast = True
            outstring += imagelist_access_list(files, starti, endi) + "&lt;br /&gt;"
        else:
            outstring += "&lt;br /&gt;&lt;br /&gt;"
            outstring += imagelist_access_list(files, starti, total_rows) + "&lt;br /&gt;"
        
        if int(page) &gt; 1:
            outstring += "&lt;a href='"
            outstring += "image_list?&amp;amp;page=1&amp;amp;item_per_page=" + \
                              str(item_per_page) + "&amp;amp;keyword=" + str(session.get('image_keyword'))
            outstring += "'&gt;&lt;&lt;&lt;/a&gt; "
            page_num = int(page) - 1
            outstring += "&lt;a href='"
            outstring += "image_list?&amp;amp;page=" + str(page_num) + \
                              "&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('image_keyword'))
            outstring += "'&gt;Previous&lt;/a&gt; "
        span = 10
        for index in range(int(page)-span, int(page)+span):
            if index &gt;=0 and index &lt; totalpage:
                page_now = index + 1
                if page_now == int(page):
                    outstring += "&lt;font size='+1' color='red'&gt;" + str(page) + " &lt;/font&gt;"
                else:
                    outstring += "&lt;a href='"
                    outstring += "image_list?&amp;amp;page=" + str(page_now) + \
                                      "&amp;amp;item_per_page=" + str(item_per_page) + \
                                      "&amp;amp;keyword=" + str(session.get('image_keyword'))
                    outstring += "'&gt;"+str(page_now) + "&lt;/a&gt; "
        if notlast == True:
            nextpage = int(page) + 1
            outstring += " &lt;a href='"
            outstring += "image_list?&amp;amp;page=" + str(nextpage) + \
                              "&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('image_keyword'))
            outstring += "'&gt;Next&lt;/a&gt;"
            outstring += " &lt;a href='"
            outstring += "image_list?&amp;amp;page=" + str(totalpage) + \
                              "&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('image_keyword'))
            outstring += "'&gt;&gt;&gt;&lt;/a&gt;"
    else:
        outstring += "no data!"
    outstring += "&lt;br /&gt;&lt;br /&gt;&lt;input type='submit' value='delete'&gt;&lt;input type='reset' value='reset'&gt;&lt;/form&gt;"

    head, level, page = parse_content()
    directory = render_menu(head, level, page)

    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;"+ \
             directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Image List&lt;/h1&gt;" + \
             outstring + "&lt;br/&gt;&lt;br /&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.29">@app.route('/imageaxupload', methods=['POST'])
# ajax jquery chunked file upload for flask
def imageaxupload():
    if isAdmin():
        # need to consider if the uploaded filename already existed.
        # right now all existed files will be replaced with the new files
        filename = request.args.get("ax-file-name")
        flag = request.args.get("start")
        if flag == "0":
            file = open(_curdir + "/images/" + filename, "wb")
        else:
            file = open(_curdir + "/images/" + filename, "ab")
        file.write(request.stream.read())
        file.close()
        return "image files uploaded!"
    else:
        return redirect("/login")


</t>
<t tx="leo.20181104192502.3">@app.route('/delete_file', methods=['POST'])
def delete_file():
    """Delete user uploaded files."""
    if not isAdmin():
        return redirect("/login")
    head, level, page = parse_content()
    directory = render_menu(head, level, page)
    filename = request.form['filename']
    if filename is None:
        outstring = "no file selected!"
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                   directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Delete Error&lt;/h1&gt;" + \
                   outstring + "&lt;br/&gt;&lt;br /&gt;&lt;/body&gt;&lt;/html&gt;"
    outstring = "delete all these files?&lt;br /&gt;&lt;br /&gt;"
    outstring += "&lt;form method='post' action='doDelete'&gt;"
    # only one file is selected
    if isinstance(filename, str):
        outstring += filename + "&lt;input type='hidden' name='filename' value='" + \
                            filename + "'&gt;&lt;br /&gt;"
    else:
        # multiple files selected
        for index in range(len(filename)):
            outstring += filename[index] + "&lt;input type='hidden' name='filename' value='" + \
                                filename[index]+"'&gt;&lt;br /&gt;"
    outstring += "&lt;br /&gt;&lt;input type='submit' value='delete'&gt;&lt;/form&gt;"

    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
               directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Download List&lt;/h1&gt;" + \
               outstring + "&lt;br/&gt;&lt;br /&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.30">def imagelist_access_list(files, starti, endi):
    # different extension files, associated links were provided
    # popup window to view images, video or STL files, other files can be downloaded directly
    # files are all the data to list, from starti to endi
    # add file size
    outstring = ""
    for index in range(int(starti)-1, int(endi)):
        fileName, fileExtension = os.path.splitext(files[index])
        fileExtension = fileExtension.lower()
        fileSize = sizeof_fmt(os.path.getsize(image_dir + "/" + files[index]))
        # images files
        if fileExtension == ".png" or fileExtension == ".jpg" or fileExtension == ".gif":
            outstring += '&lt;input type="checkbox" name="filename" value="' + files[index] + \
                              '"&gt;&lt;a href="javascript:;" onClick="window.open(\'/images/' + \
                              files[index] + '\',\'images\', \'catalogmode\',\'scrollbars\')"&gt;' + \
                              files[index] + '&lt;/a&gt; (' + str(fileSize) + ')&lt;br /&gt;'
    return outstring


# 與 file_selector 搭配的取影像檔程式
</t>
<t tx="leo.20181104192502.31">def imageselect_access_list(files, starti, endi):
    outstring = '''&lt;head&gt;
&lt;style&gt;
a.xhfbfile {padding: 0 2px 0 0; line-height: 1em;}
a.xhfbfile img{border: none; margin: 6px;}
a.xhfbfile span{display: none;}
a.xhfbfile:hover span{
    display: block;
    position: relative;
    left: 150px;
    border: #aaa 1px solid;
    padding: 2px;
    background-color: #ddd;
}
a.xhfbfile:hover{
    background-color: #ccc;
    opacity: .9;
    cursor:pointer;
}
&lt;/style&gt;
&lt;/head&gt;
'''
    for index in range(int(starti)-1, int(endi)):
        fileName, fileExtension = os.path.splitext(files[index])
        fileSize = os.path.getsize(image_dir+"/"+files[index])
        outstring += '''&lt;a class="xhfbfile" href="#" onclick='window.setLink("/images/'''+ \
                          files[index] + '''",0); return false;'&gt;''' + \
                          files[index] + '''&lt;span style="position: absolute; z-index: 4;"&gt;&lt;br /&gt; \
                          &lt;img src="/images/''' + files[index] + '''" width="150px"/&gt;&lt;/span&gt;&lt;/a&gt; \
                          (''' + str(sizeof_fmt(fileSize)) + ''')&lt;br /&gt;'''
    return outstring


</t>
<t tx="leo.20181104192502.32">@app.route('/imageuploadform', defaults={'edit': 1})
@app.route('/imageuploadform/&lt;path:edit&gt;')
def imageuploadform(edit):
    """image files upload form"""
    if isAdmin():
        head, level, page = parse_content()
        directory = render_menu(head, level, page)
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                 directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;image files upload&lt;/h1&gt;" + '''
&lt;script src="/static/jquery.js" type="text/javascript"&gt;&lt;/script&gt;
&lt;script src="/static/axuploader.js" type="text/javascript"&gt;&lt;/script&gt;
&lt;script&gt;
$(document).ready(function(){
$('.prova').axuploader({url:'imageaxupload', allowExt:['jpg','png','gif'],
finish:function(x,files)
    {
        alert('All files have been uploaded: '+files);
    },
enable:true,
remotePath:function(){
return 'images/';
}
});
});
&lt;/script&gt;
&lt;div class="prova"&gt;&lt;/div&gt;
&lt;input type="button" onclick="$('.prova').axuploader('disable')" value="asd" /&gt;
&lt;input type="button" onclick="$('.prova').axuploader('enable')" value="ok" /&gt;
&lt;/section&gt;&lt;/body&gt;&lt;/html&gt;
'''
    else:
        return redirect("/login")


</t>
<t tx="leo.20181104192502.33">@app.route('/')
def index():
    head, level, page = parse_content()
    # fix first Chinese heading error
    return redirect("/get_page/" + urllib.parse.quote_plus(head[0]))
    # the following will never execute
    directory = render_menu(head, level, page)
    if heading is None:
        heading = head[0]
    # 因為同一 heading 可能有多頁, 因此不可使用 head.index(heading) 搜尋 page_order
    page_order_list, page_content_list = search_content(head, page, heading)
    return_content = ""
    for i in range(len(page_order_list)):
        #page_order = head.index(heading)
        page_order = page_order_list[page_order_list[i]]
        if page_order == 0:
            last_page = ""
        else:
            last_page = head[page_order-1] + " &lt;&lt; &lt;a href='/get_page/" + \
                             head[page_order-1] + "'&gt;Previous&lt;/a&gt;"
        if page_order == len(head) - 1:
            # no next page
            next_page = ""
        else:
            next_page = "&lt;a href='/get_page/" + head[page_order+1] + \
                              "'&gt;Next&lt;/a&gt; &gt;&gt; " + head[page_order+1]
        return_content += last_page + " " + next_page + "&lt;br /&gt;&lt;h1&gt;" + \
                                  heading + "&lt;/h1&gt;" + page_content_list[page_order_list[i]] + \
                                  "&lt;br /&gt;" + last_page + " " + next_page

    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
             directory + "&lt;/nav&gt;&lt;section&gt;" + return_content + "&lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.34">def isAdmin():
    if session.get('admin') == 1:
            return True
    else:
        return False


# use to check directory variable data
</t>
<t tx="leo.20181104192502.35">@app.route('/listdir')
def listdir():
    return download_dir + "," + config_dir


</t>
<t tx="leo.20181104192502.36">@app.route('/load_list')
def load_list(item_per_page=5, page=1, filedir=None, keyword=None):
    files = os.listdir(config_dir+filedir+"_programs/")
    if keyword is None:
        pass
    else:
        session['search_keyword'] = keyword
        files = [s for s in files if keyword in s]
    total_rows = len(files)
    totalpage = math.ceil(total_rows/int(item_per_page))
    starti = int(item_per_page) * (int(page) - 1) + 1
    endi = starti + int(item_per_page) - 1
    outstring = '''&lt;script&gt;
function keywordSearch(){
    var oform = document.forms["searchform"];
    // 取elements集合中 name 屬性為 keyword 的值
    var getKeyword = oform.elements.keyword.value;
    // 改為若表單為空, 則列出全部資料
    //if(getKeyword != ""){
        window.location = "?brython&amp;keyword="+getKeyword;
    //}
}
&lt;/script&gt;
    &lt;form name="searchform"&gt;
    &lt;input type="text" id="keyword" /&gt;
    &lt;input type="button" id="send" value="查詢" onClick="keywordSearch()"/&gt; 
    &lt;/form&gt;
'''
    outstring += "&lt;form name='filelist' method='post' action=''&gt;"
    notlast = False
    if total_rows &gt; 0:
        # turn off the page selector on top
        '''
        outstring += "&lt;br /&gt;"
        if (int(page) * int(item_per_page)) &lt; total_rows:
            notlast = True
        if int(page) &gt; 1:
            outstring += "&lt;a href='"
            outstring += "brython?&amp;amp;page=1&amp;amp;item_per_page="+str(item_per_page)+"&amp;amp;keyword="+str(session.get('search_keyword'))
            outstring += "'&gt;{{&lt;/a&gt; "
            page_num = int(page) - 1
            outstring += "&lt;a href='"
            outstring += "brython?&amp;amp;page="+str(page_num)+"&amp;amp;item_per_page="+str(item_per_page)+"&amp;amp;keyword="+str(session.get('search_keyword'))
            outstring += "'&gt;Previous&lt;/a&gt; "
        span = 10
        for index in range(int(page)-span, int(page)+span):
            if index&gt;= 0 and index&lt; totalpage:
                page_now = index + 1 
                if page_now == int(page):
                    outstring += "&lt;font size='+1' color='red'&gt;"+str(page)+" &lt;/font&gt;"
                else:
                    outstring += "&lt;a href='"
                    outstring += "brython?&amp;amp;page="+str(page_now)+"&amp;amp;item_per_page="+str(item_per_page)+"&amp;amp;keyword="+str(session.get('search_keyword'))
                    outstring += "'&gt;"+str(page_now)+"&lt;/a&gt; "

        if notlast == True:
            nextpage = int(page) + 1
            outstring += " &lt;a href='"
            outstring += "brython?&amp;amp;page="+str(nextpage)+"&amp;amp;item_per_page="+str(item_per_page)+"&amp;amp;keyword="+str(session.get('search_keyword'))
            outstring += "'&gt;Next&lt;/a&gt;"
            outstring += " &lt;a href='"
            outstring += "brython?&amp;amp;page="+str(totalpage)+"&amp;amp;item_per_page="+str(item_per_page)+"&amp;amp;keyword="+str(session.get('search_keyword'))
            outstring += "'&gt;}}&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;"
        '''
        if (int(page) * int(item_per_page)) &lt; total_rows:
            notlast = True
            outstring += loadlist_access_list(files, starti, endi, filedir) + "&lt;br /&gt;"
        else:
            outstring += "&lt;br /&gt;&lt;br /&gt;"
            outstring += loadlist_access_list(files, starti, total_rows, filedir) + "&lt;br /&gt;"
        
        if int(page) &gt; 1:
            outstring += "&lt;a href='"
            outstring += "/"+filedir + "?&amp;amp;page=1&amp;amp;item_per_page=" + str(item_per_page)+"&amp;amp;keyword=" + str(session.get('search_keyword'))
            outstring += "'&gt;{{&lt;/a&gt; "
            page_num = int(page) - 1
            outstring += "&lt;a href='"
            outstring += "/"+filedir + "?&amp;amp;page=" + str(page_num)+"&amp;amp;item_per_page=" + \
                              str(item_per_page) + "&amp;amp;keyword=" + str(session.get('search_keyword'))
            outstring += "'&gt;Previous&lt;/a&gt; "
        span = 5
        for index in range(int(page)-span, int(page)+span):
        #for ($j=$page-$range;$j&lt;$page+$range;$j++)
            if index &gt;=0 and index &lt; totalpage:
                page_now = index + 1
                if page_now == int(page):
                    outstring += "&lt;font size='+1' color='red'&gt;" + str(page) + " &lt;/font&gt;"
                else:
                    outstring += "&lt;a href='"
                    outstring += "/" + filedir + "?&amp;amp;page=" + str(page_now) + \
                                      "&amp;amp;item_per_page=" + str(item_per_page) + \
                                      "&amp;amp;keyword="+str(session.get('search_keyword'))
                    outstring += "'&gt;" + str(page_now) + "&lt;/a&gt; "
        if notlast == True:
            nextpage = int(page) + 1
            outstring += " &lt;a href='"
            outstring += "/" + filedir + "?&amp;amp;page=" + str(nextpage) + \
                              "&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('search_keyword'))
            outstring += "'&gt;Next&lt;/a&gt;"
            outstring += " &lt;a href='"
            outstring += "/" + filedir + "?&amp;amp;page=" + str(totalpage) + \
                              "&amp;amp;item_per_page=" + str(item_per_page) + \
                              "&amp;amp;keyword=" + str(session.get('search_keyword'))
            outstring += "'&gt;}}&lt;/a&gt;"
    else:
        outstring += "no data!"
    #outstring += "&lt;br /&gt;&lt;br /&gt;&lt;input type='submit' value='load'&gt;&lt;input type='reset' value='reset'&gt;&lt;/form&gt;"
    outstring += "&lt;br /&gt;&lt;br /&gt;&lt;/form&gt;"

    return outstring


</t>
<t tx="leo.20181104192502.37">def loadlist_access_list(files, starti, endi, filedir):
    # different extension files, associated links were provided
    # popup window to view images, video or STL files, other files can be downloaded directly
    # files are all the data to list, from starti to endi
    # add file size
    outstring = ""
    for index in range(int(starti)-1, int(endi)):
        fileName, fileExtension = os.path.splitext(files[index])
        fileExtension = fileExtension.lower()
        fileSize = sizeof_fmt(os.path.getsize(config_dir + filedir + "_programs/" + files[index]))
        # images files
        if fileExtension == ".png" or fileExtension == ".jpg" or fileExtension == ".gif":
            outstring += '&lt;input type="checkbox" name="filename" value="' + files[index] + \
                              '"&gt;&lt;a href="javascript:;" onClick="window.open(\'/downloads/'+ \
                            files[index] + '\',\'images\', \'catalogmode\',\'scrollbars\')"&gt;' + files[index] + '&lt;/a&gt; (' + str(fileSize)+')&lt;br /&gt;'
        # stl files
        elif fileExtension == ".stl":
            outstring += '&lt;input type="checkbox" name="filename" value="' + files[index] + '"&gt;&lt;a href="javascript:;" onClick="window.open(\'/static/viewstl.html?src=/downloads/' + \
            files[index] + '\',\'images\', \'catalogmode\',\'scrollbars\')"&gt;' + files[index] + '&lt;/a&gt; ('+str(fileSize)+')&lt;br /&gt;'
        # flv files
        elif fileExtension == ".flv":
            outstring += '&lt;input type="checkbox" name="filename" value="' + files[index] + '"&gt;&lt;a href="javascript:;" onClick="window.open(\'/flvplayer?filepath=/downloads/' + \
            files[index]+'\',\'images\', \'catalogmode\',\'scrollbars\')"&gt;' + files[index] + '&lt;/a&gt; ('+str(fileSize)+')&lt;br /&gt;'
        # py files
        elif fileExtension == ".py":
            outstring += '&lt;input type="radio" name="filename" value="' + files[index] + '"&gt;' + files[index] + ' (' + str(fileSize) + ')&lt;br /&gt;'
        # direct download files
        else:
            outstring += "&lt;input type='checkbox' name='filename' value='" + files[index] + \
                             "'&gt;&lt;a href='/" + filedir + "_programs/" + files[index] + "'&gt;" + files[index] + "&lt;/a&gt; (" + str(fileSize) + ")&lt;br /&gt;"
    return outstring


</t>
<t tx="leo.20181104192502.38">@app.route('/login')
def login():
    """login routine"""
    head, level, page = parse_content()
    directory = render_menu(head, level, page)
    if not isAdmin():
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                 directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Login&lt;/h1&gt;&lt;form method='post' action='checkLogin'&gt; \
                Password:&lt;input type='password' name='password'&gt; \
    &lt;input type='submit' value='login'&gt;&lt;/form&gt; \
    &lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"
    else:
        return redirect('/edit_page')


</t>
<t tx="leo.20181104192502.39">@app.route('/logout')
def logout():
    session.pop('admin' , None)
    flash('已經登出!')
    return redirect(url_for('login'))


</t>
<t tx="leo.20181104192502.4">@app.route('/doDelete', methods=['POST'])
def doDelete():
    """Action to delete user uploaded files."""
    if not isAdmin():
        return redirect("/login")
    # delete files
    filename = request.form['filename']
    outstring = "all these files will be deleted:&lt;br /&gt;&lt;br /&gt;"
    # only select one file
    if isinstance(filename, str):
        try:
            os.remove(download_dir + "/" + filename)
            outstring += filename + " deleted!"
        except:
            outstring += filename + "Error, can not delete files!&lt;br /&gt;"
    else:
        # multiple files selected
        for index in range(len(filename)):
            try:
                os.remove(download_dir + "/" + filename[index])
                outstring += filename[index] + " deleted!&lt;br /&gt;"
            except:
                outstring += filename[index] + "Error, can not delete files!&lt;br /&gt;"

    head, level, page = parse_content()
    directory = render_menu(head, level, page)

    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
               directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Download List&lt;/h1&gt;" + \
               outstring + "&lt;br/&gt;&lt;br /&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.40">def parse_config():
    if not os.path.isfile(config_dir+"config"):
        # create config file if there is no config file
        file = open(config_dir + "config", "w", encoding="utf-8")
        # default password is admin
        password="admin"
        hashed_password = hashlib.sha512(password.encode('utf-8')).hexdigest()
        file.write("siteTitle:CMSimfly \npassword:"+hashed_password)
        file.close()
    config = file_get_contents(config_dir + "config")
    config_data = config.split("\n")
    site_title = config_data[0].split(":")[1]
    password = config_data[1].split(":")[1]
    return site_title, password


</t>
<t tx="leo.20181104192502.41">def _remove_h123_attrs(soup):
    tag_order = 0
    for tag in soup.find_all(['h1', 'h2', 'h3']):
        # 假如標註內容沒有字串
        #if len(tag.text) == 0:
        if len(tag.contents) ==0:
            # 且該標註為排序第一
            if tag_order == 0:
                tag.string = "First"
            else:
                # 若該標註非排序第一, 則移除無內容的標題標註
                tag.extract()
        # 針對單一元件的標題標註
        elif len(tag.contents) == 1:
            # 若內容非為純文字, 表示內容為其他標註物件
            if tag.get_text() == "":
                # 且該標註為排序第一
                if tag_order == 0:
                    # 在最前方插入標題
                    tag.insert_before(soup.new_tag('h1', 'First'))
                else:
                    # 移除 h1, h2 或 h3 標註, 只留下內容
                    tag.replaceWithChildren()
            # 表示單一元件的標題標註, 且標題為單一字串者
            else:
                # 判定若其排序第一, 則將 tag.name 為 h2 或 h3 者換為 h1
                if tag_order == 0:
                    tag.name = "h1"
            # 針對其餘單一字串內容的標註, 則保持原樣
        # 針對內容一個以上的標題標註
        #elif len(tag.contents) &gt; 1:
        else:
            # 假如該標註內容長度大於 1
            # 且該標註為排序第一
            if tag_order == 0:
                # 先移除 h1, h2 或 h3 標註, 只留下內容
                #tag.replaceWithChildren()
                # 在最前方插入標題
                tag.insert_before(soup.new_tag('h1', 'First'))
            else:
                # 只保留標題內容,  去除 h1, h2 或 h3 標註
                # 為了與前面的內文區隔, 先在最前面插入 br 標註
                tag.insert_before(soup.new_tag('br'))
                # 再移除非排序第一的 h1, h2 或 h3 標註, 只留下內容
                tag.replaceWithChildren()
        tag_order = tag_order + 1

    return soup

</t>
<t tx="leo.20181104192502.42">def parse_content():
    """use bs4 and re module functions to parse content.htm"""
    #from pybean import Store, SQLiteWriter
    # if no content.db, create database file with cms table
    '''
    if not os.path.isfile(config_dir+"content.db"):
        library = Store(SQLiteWriter(config_dir+"content.db", frozen=False))
        cms = library.new("cms")
        cms.follow = 0
        cms.title = "head 1"
        cms.content = "content 1"
        cms.memo = "first memo"
        library.save(cms)
        library.commit()
    '''
    # if no content.htm, generate a head 1 and content 1 file
    if not os.path.isfile(config_dir+"content.htm"):
        # create content.htm if there is no content.htm
        File = open(config_dir + "content.htm", "w", encoding="utf-8")
        File.write("&lt;h1&gt;head 1&lt;/h1&gt;content 1")
        File.close()
    subject = file_get_contents(config_dir+"content.htm")
    # deal with content without content
    if subject == "":
        # create content.htm if there is no content.htm
        File = open(config_dir + "content.htm", "w", encoding="utf-8")
        File.write("&lt;h1&gt;head 1&lt;/h1&gt;content 1")
        File.close()
        subject = "&lt;h1&gt;head 1&lt;/h1&gt;content 1"
    # initialize the return lists
    head_list = []
    level_list = []
    page_list = []
    # make the soup out of the html content
    soup = bs4.BeautifulSoup(subject, 'html.parser')
    # 嘗試解讀各種情況下的標題
    soup = _remove_h123_attrs(soup)
    # 改寫 content.htm 後重新取 subject
    with open(config_dir + "content.htm", "wb") as f:
        f.write(soup.encode("utf-8"))
    subject = file_get_contents(config_dir+"content.htm")
    # get all h1, h2, h3 tags into list
    htag= soup.find_all(['h1', 'h2', 'h3'])
    n = len(htag)
    # get the page content to split subject using each h tag
    temp_data = subject.split(str(htag[0]))
    if len(temp_data) &gt; 2:
        subject = str(htag[0]).join(temp_data[1:])
    else:
        subject = temp_data[1]
    if n &gt;1:
            # i from 1 to i-1
            for i in range(1, len(htag)):
                head_list.append(htag[i-1].text.strip())
                # use name attribute of h* tag to get h1, h2 or h3
                # the number of h1, h2 or h3 is the level of page menu
                level_list.append(htag[i-1].name[1])
                temp_data = subject.split(str(htag[i]))
                if len(temp_data) &gt; 2:
                    subject = str(htag[i]).join(temp_data[1:])
                else:
                    subject = temp_data[1]
                # cut the other page content out of htag from 1 to i-1
                cut = temp_data[0]
                # add the page content
                page_list.append(cut)
    # last i
    # add the last page title
    head_list.append(htag[n-1].text.strip())
    # add the last level
    level_list.append(htag[n-1].name[1])
    temp_data = subject.split(str(htag[n-1]))
    # the last subject
    subject = temp_data[0]
    # cut the last page content out
    cut = temp_data[0]
    # the last page content
    page_list.append(cut)
    return head_list, level_list, page_list

</t>
<t tx="leo.20181104192502.43">def render_menu(head, level, page, sitemap=0):
    '''允許使用者在 h1 標題後直接加上 h3 標題, 或者隨後納入 h4 之後作為標題標註'''
    directory = ""
    # 從 level 數列第一個元素作為開端
    current_level = level[0]
    # 若是 sitemap 則僅列出樹狀架構而沒有套用 css3menu 架構
    if sitemap:
        directory += "&lt;ul&gt;"
    else:
        directory += "&lt;ul id='css3menu1' class='topmenu'&gt;"
    # 逐一配合 level 數列中的各標題階次, 一一建立對應的表單或 sitemap
    for index in range(len(head)):
        # 用 this_level 取出迴圈中逐一處理的頁面對應層級, 注意取出值為 str
        this_level = level[index]
        # 若處理中的層級比上一層級高超過一層, 則將處理層級升級 (處理 h1 後直接接 h3 情況)
        if (int(this_level) - int(current_level)) &gt; 1:
            #this_level = str(int(this_level) - 1)
            # 考慮若納入 h4 也作為標題標註, 相鄰層級可能大於一層, 因此直接用上一層級 + 1
            this_level = str(int(current_level) + 1)
        # 若處理的階次比目前已經處理的階次大, 表示位階較低
        # 其實當 level[0] 完全不會報告此一區塊
        # 從正在處理的標題階次與前一個元素比對, 若階次低, 則要加入另一區段的 unordered list 標頭
        # 兩者皆為 str 會轉為整數後比較
        if this_level &gt; current_level:
            directory += "&lt;ul&gt;"
            directory += "&lt;li&gt;&lt;a href='/get_page/" + head[index] + "'&gt;" + head[index] + "&lt;/a&gt;"
        # 假如正在處理的標題與前一個元素同位階, 則必須再判定是否為另一個 h1 的樹狀頭
        elif this_level == current_level:
            # 若正在處理的標題確實為樹狀頭, 則標上樹狀頭開始標註
            if this_level == 1:
                # 這裡還是需要判定是在建立 sitemap 模式或者選單模式
                if sitemap:
                    directory += "&lt;li&gt;&lt;a href='/get_page/" + head[index] + "'&gt;" + head[index]+"&lt;/a&gt;"
                else:
                    directory += "&lt;li class='topmenu'&gt;&lt;a href='/get_page/" + head[index] + "'&gt;" + head[index] + "&lt;/a&gt;"
            #  假如不是樹狀頭, 則只列出對應的 list
            else:
                directory += "&lt;li&gt;&lt;a href='/get_page/" + head[index] + "'&gt;" + head[index] + "&lt;/a&gt;"
        # 假如正處理的元素比上一個元素位階更高, 必須要先關掉前面的低位階區段
        else:
            directory += "&lt;/li&gt;"*(int(current_level) - int(level[index]))
            directory += "&lt;/ul&gt;"*(int(current_level) - int(level[index]))
            if this_level == 1:
                if sitemap:
                    directory += "&lt;li&gt;&lt;a href='/get_page/" + head[index] + "'&gt;" + head[index] + "&lt;/a&gt;"
                else:
                    directory += "&lt;li class='topmenu'&gt;&lt;a href='/get_page/" + head[index] + "'&gt;" + head[index] + "&lt;/a&gt;"
            else:
                directory += "&lt;li&gt;&lt;a href='/get_page/" + head[index] + "'&gt;" + head[index] + "&lt;/a&gt;"
        current_level = this_level
    directory += "&lt;/li&gt;&lt;/ul&gt;"
    return directory
</t>
<t tx="leo.20181104192502.44">def render_menu2(head, level, page, sitemap=0):
    """render menu for static site"""
    directory = ""
    current_level = level[0]
    if sitemap:
        directory += "&lt;ul&gt;"
    else:
        directory += "&lt;ul id='css3menu1' class='topmenu'&gt;"
    for index in range(len(head)):
        this_level = level[index]
        # 若處理中的層級比上一層級高超過一層, 則將處理層級升級 (處理 h1 後直接接 h3 情況)
        if (int(this_level) - int(current_level)) &gt; 1:
            #this_level = str(int(this_level) - 1)
            this_level = str(int(current_level) + 1)
        if this_level &gt; current_level:
            directory += "&lt;ul&gt;"
            #directory += "&lt;li&gt;&lt;a href='/get_page/"+head[index]+"'&gt;"+head[index]+"&lt;/a&gt;"
            # 改為連結到 content/標題.html
            directory += "&lt;li&gt;&lt;a href='" + head[index] + ".html'&gt;" + head[index] + "&lt;/a&gt;"
        elif this_level == current_level:
            if this_level == 1:
                if sitemap:
                    # 改為連結到 content/標題.html
                    #directory += "&lt;li&gt;&lt;a href='/get_page/"+head[index]+"'&gt;"+head[index]+"&lt;/a&gt;"
                    directory += "&lt;li&gt;&lt;a href='" + head[index] + ".html'&gt;" + head[index] + "&lt;/a&gt;"
                else:
                    #directory += "&lt;li class='topmenu'&gt;&lt;a href='/get_page/"+head[index]+"'&gt;"+head[index]+"&lt;/a&gt;"
                    directory += "&lt;li class='topmenu'&gt;&lt;a href='content/" + head[index] + ".html'&gt;" + head[index] + "&lt;/a&gt;"
            else:
                #directory += "&lt;li&gt;&lt;a href='/get_page/"+head[index]+"'&gt;"+head[index]+"&lt;/a&gt;"
                directory += "&lt;li&gt;&lt;a href='" + head[index] + ".html'&gt;" + head[index] + "&lt;/a&gt;"
        else:
            directory += "&lt;/li&gt;"*(int(current_level) - int(level[index]))
            directory += "&lt;/ul&gt;"*(int(current_level) - int(level[index]))
            if this_level == 1:
                if sitemap:
                    #directory += "&lt;li&gt;&lt;a href='/get_page/"+head[index]+"'&gt;"+head[index]+"&lt;/a&gt;"
                    directory += "&lt;li&gt;&lt;a href='" + head[index] + ".html'&gt;" + head[index] + "&lt;/a&gt;"
                else:
                    #directory += "&lt;li class='topmenu'&gt;&lt;a href='/get_page/"+head[index]+"'&gt;"+head[index]+"&lt;/a&gt;"
                    directory += "&lt;li class='topmenu'&gt;&lt;a href='" + head[index] + ".html'&gt;" + head[index] + "&lt;/a&gt;"
            else:
                #directory += "&lt;li&gt;&lt;a href='/get_page/"+head[index]+"'&gt;"+head[index]+"&lt;/a&gt;"
                directory += "&lt;li&gt;&lt;a href='" + head[index] + ".html'&gt;" + head[index] + "&lt;/a&gt;"
        current_level = this_level
    directory += "&lt;/li&gt;&lt;/ul&gt;"
    return directory
</t>
<t tx="leo.20181104192502.45">@app.route('/saveConfig', methods=['POST'])
def saveConfig():
    if not isAdmin():
        return redirect("/login")
    site_title = request.form['site_title']
    password = request.form['password']
    password2 = request.form['password2']
    if site_title is None or password is None:
        return error_log("no content to save!")
    old_site_title, old_password = parse_config()
    head, level, page = parse_content()
    directory = render_menu(head, level, page)
    if site_title is None or password is None or password2 != old_password or password == '':
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Error!&lt;/h1&gt;&lt;a href='/'&gt;Home&lt;/a&gt;&lt;/body&gt;&lt;/html&gt;"
    else:
        if password == password2 and password == old_password:
            hashed_password = old_password
        else:
            hashed_password = hashlib.sha512(password.encode('utf-8')).hexdigest()
        file = open(config_dir + "config", "w", encoding="utf-8")
        file.write("siteTitle:" + site_title + "\npassword:" + hashed_password)
        file.close()
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                 directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;config file saved&lt;/h1&gt;&lt;a href='/'&gt;Home&lt;/a&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.46">@app.route('/savePage', methods=['POST'])
def savePage():
    """save all pages function"""
    page_content = request.form['page_content']
    # check if administrator
    if not isAdmin():
        return redirect("/login")
    if page_content is None:
        return error_log("no content to save!")
    # 在插入新頁面資料前, 先複製 content.htm 一分到 content_backup.htm
    shutil.copy2(config_dir + "content.htm", config_dir + "content_backup.htm")
    file = open(config_dir + "content.htm", "w", encoding="utf-8")
    # in Windows client operator, to avoid textarea add extra \n
    page_content = page_content.replace("\n","")
    file.write(page_content)
    file.close()

    # if every savePage generate_pages needed
    #generate_pages()
    '''
    # need to parse_content() to eliminate duplicate heading
    head, level, page = parse_content()
    file = open(config_dir + "content.htm", "w", encoding="utf-8")
    for index in range(len(head)):
        file.write("&lt;h" + str(level[index])+ "&gt;" + str(head[index]) + "&lt;/h" + str(level[index]) + "&gt;" + str(page[index]))
    file.close()
    '''
    return redirect("/edit_page")


# use head title to search page content
'''
# search_content(head, page, search)
# 從 head 與 page 數列中, 以 search 關鍵字進行查詢
# 原先傳回與 search 關鍵字頁面對應的頁面內容
# 現在則傳回多重的頁面次序與頁面內容數列
find = lambda searchList, elem: [[i for i, x in enumerate(searchList) if x == e] for e in elem]
head = ["標題一","標題二","標題三","標題一","標題四","標題五"]
search_result = find(head,["標題一"])[0]
page_order = []
page_content = []
for i in range(len(search_result)):
    # 印出次序
    page_order.append(search_result[i])
    # 標題為 head[search_result[i]]
    #  頁面內容則為 page[search_result[i]]
    page_content.append(page[search_result[i]])
    # 從 page[次序] 印出頁面內容
# 準備傳回 page_order 與 page_content 等兩個數列
'''


</t>
<t tx="leo.20181104192502.47">def search_content(head, page, search):
    """search content"""
    ''' 舊內容
    return page[head.index(search)]
    '''
    find = lambda searchList, elem: [[i for i, x in enumerate(searchList) if x == e] for e in elem]
    search_result = find(head, [search])[0]
    page_order = []
    page_content = []
    for i in range(len(search_result)):
        # 印出次序
        page_order.append(search_result[i])
        # 標題為 head[search_result[i]]
        #  頁面內容則為 page[search_result[i]]
        page_content.append(page[search_result[i]])
        # 從 page[次序] 印出頁面內容
    # 準備傳回 page_order 與 page_content 等兩個數列
    return page_order, page_content


</t>
<t tx="leo.20181104192502.48">@app.route('/search_form', defaults={'edit': 1})
@app.route('/search_form/&lt;path:edit&gt;')
def search_form(edit):
    """form of keyword search"""
    if isAdmin():
        head, level, page = parse_content()
        directory = render_menu(head, level, page)
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                 directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Search&lt;/h1&gt; \
                 &lt;form method='post' action='doSearch'&gt; \
                 keywords:&lt;input type='text' name='keyword'&gt; \
                 &lt;input type='submit' value='search'&gt;&lt;/form&gt; \
                 &lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"
    else:
        return redirect("/login")


# setup static directory
</t>
<t tx="leo.20181104192502.49">@app.route('/static/&lt;path:path&gt;')
def send_file(path):
    """send file function"""
    return app.send_static_file(static_dir + path)


# setup static directory
#@app.route('/images/&lt;path:path&gt;')
</t>
<t tx="leo.20181104192502.5">@app.route('/doSearch', methods=['POST'])
def doSearch():
    """Action to search content.htm using keyword"""
    if not isAdmin():
        return redirect("/login")
    else:
        keyword = request.form['keyword']
        head, level, page = parse_content()
        directory = render_menu(head, level, page)
        match = ""
        for index in range(len(head)):
            if (keyword != "" or None) and (keyword.lower() in page[index].lower() or \
            keyword.lower() in head[index].lower()): \
                match += "&lt;a href='/get_page/" + head[index] + "'&gt;" + \
                                head[index] + "&lt;/a&gt;&lt;br /&gt;"
        return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;"+ \
                   directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Search Result&lt;/h1&gt;keyword: " + \
                   keyword.lower() + "&lt;br /&gt;&lt;br /&gt;in the following pages:&lt;br /&gt;&lt;br /&gt;" + \
                   match + "&lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.50">@app.route('/images/&lt;path:path&gt;')
def send_images(path):
    """send image files"""
    return send_from_directory(_curdir + "/images/", path)


# setup static directory
</t>
<t tx="leo.20181104192502.51">@app.route('/static/')
def send_static():
    """send static files"""
    return app.send_static_file('index.html')


# set_admin_css for administrator
</t>
<t tx="leo.20181104192502.52">def set_admin_css():
    """set css for admin"""
    outstring = '''&lt;!doctype html&gt;
&lt;html&gt;&lt;head&gt;
&lt;meta http-equiv="content-type" content="text/html;charset=utf-8"&gt;
&lt;title&gt;期末分組專案&lt;/title&gt; \
&lt;link rel="stylesheet" type="text/css" href="/static/cmsimply.css"&gt;
''' + syntaxhighlight()

    outstring += '''
&lt;script src="/static/jquery.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript"&gt;
$(function(){
    $("ul.topmenu&gt; li:has(ul) &gt; a").append('&lt;div class="arrow-right"&gt;&lt;/div&gt;');
    $("ul.topmenu &gt; li ul li:has(ul) &gt; a").append('&lt;div class="arrow-right"&gt;&lt;/div&gt;');
});
&lt;/script&gt;
'''
    # SSL for uwsgi operation
    if uwsgi:
        outstring += '''
&lt;script type="text/javascript"&gt;
if ((location.href.search(/http:/) != -1) &amp;&amp; (location.href.search(/login/) != -1)) \
window.location= 'https://' + location.host + location.pathname + location.search;
&lt;/script&gt;
'''
    site_title, password = parse_config()
    outstring += '''
&lt;/head&gt;&lt;header&gt;&lt;h1&gt;''' + site_title + '''&lt;/h1&gt; \
&lt;confmenu&gt;
&lt;ul&gt;
&lt;li&gt;&lt;a href="/"&gt;Home&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/sitemap"&gt;SiteMap&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/edit_page"&gt;Edit All&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="''' + str(request.url) + '''/1"&gt;Edit&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/edit_config"&gt;Config&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/search_form"&gt;Search&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/imageuploadform"&gt;Image Upload&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/image_list"&gt;Image List&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/fileuploadform"&gt;File Upload&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/download_list"&gt;File List&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/logout"&gt;Logout&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/generate_pages"&gt;generate_pages&lt;/a&gt;&lt;/li&gt;
'''
    outstring += '''
&lt;/ul&gt;
&lt;/confmenu&gt;&lt;/header&gt;
'''
    return outstring


</t>
<t tx="leo.20181104192502.53">def set_css():
    """set css for dynamic site"""
    outstring = '''&lt;!doctype html&gt;
&lt;html&gt;&lt;head&gt;
&lt;meta http-equiv="content-type" content="text/html;charset=utf-8"&gt;
&lt;title&gt;期末分組專案&lt;/title&gt; \
&lt;link rel="stylesheet" type="text/css" href="/static/cmsimply.css"&gt;
''' + syntaxhighlight()

    outstring += '''
&lt;script src="/static/jquery.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript"&gt;
$(function(){
    $("ul.topmenu&gt; li:has(ul) &gt; a").append('&lt;div class="arrow-right"&gt;&lt;/div&gt;');
    $("ul.topmenu &gt; li ul li:has(ul) &gt; a").append('&lt;div class="arrow-right"&gt;&lt;/div&gt;');
});
&lt;/script&gt;
'''
    if uwsgi:
        outstring += '''
&lt;script type="text/javascript"&gt;
if ((location.href.search(/http:/) != -1) &amp;&amp; (location.href.search(/login/) != -1)) \
window.location= 'https://' + location.host + location.pathname + location.search;
&lt;/script&gt;
'''
    site_title, password = parse_config()
    outstring += '''
&lt;/head&gt;&lt;header&gt;&lt;h1&gt;''' + site_title + '''&lt;/h1&gt; \
&lt;confmenu&gt;
&lt;ul&gt;
&lt;li&gt;&lt;a href="/"&gt;Home&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/sitemap"&gt;Site Map&lt;/a&gt;&lt;/li&gt;
'''
    if isAdmin():
        outstring += '''
&lt;li&gt;&lt;a href="/edit_page"&gt;Edit All&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="''' + str(request.url) + '''/1"&gt;Edit&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/edit_config"&gt;Config&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/search_form"&gt;Search&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/imageuploadform"&gt;image upload&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/image_list"&gt;image list&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/fileuploadform"&gt;file upload&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/download_list"&gt;file list&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/logout"&gt;logout&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="/generate_pages"&gt;generate_pages&lt;/a&gt;&lt;/li&gt;
'''
    else:
        outstring += '''
&lt;li&gt;&lt;a href="/login"&gt;login&lt;/a&gt;&lt;/li&gt;
'''
    outstring += '''
&lt;/ul&gt;
&lt;/confmenu&gt;&lt;/header&gt;
'''
    return outstring


</t>
<t tx="leo.20181104192502.54">def set_css2():
    """set css for static site"""
    outstring = '''&lt;!doctype html&gt;
&lt;html&gt;&lt;head&gt;
&lt;meta http-equiv="content-type" content="text/html;charset=utf-8"&gt;
&lt;title&gt;期末分組專案&lt;/title&gt; \
&lt;link rel="stylesheet" type="text/css" href="./../static/cmsimply.css"&gt;
''' + syntaxhighlight2()

    outstring += '''
&lt;script src="./../static/jquery.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript"&gt;
$(function(){
    $("ul.topmenu&gt; li:has(ul) &gt; a").append('&lt;div class="arrow-right"&gt;&lt;/div&gt;');
    $("ul.topmenu &gt; li ul li:has(ul) &gt; a").append('&lt;div class="arrow-right"&gt;&lt;/div&gt;');
});
&lt;/script&gt;
'''
    if uwsgi:
        outstring += '''
&lt;script type="text/javascript"&gt;
if ((location.href.search(/http:/) != -1) &amp;&amp; (location.href.search(/login/) != -1)) \
window.location= 'https://' + location.host + location.pathname + location.search;
&lt;/script&gt;
'''
    site_title, password = parse_config()
    outstring += '''
&lt;/head&gt;&lt;header&gt;&lt;h1&gt;''' + site_title + '''&lt;/h1&gt; \
&lt;confmenu&gt;
&lt;ul&gt;
&lt;li&gt;&lt;a href="index.html"&gt;Home&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="sitemap.html"&gt;Site Map&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="./../reveal/index.html"&gt;reveal&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href="./../blog/index.html"&gt;blog&lt;/a&gt;&lt;/li&gt;
'''
    outstring += '''
&lt;/ul&gt;
&lt;/confmenu&gt;&lt;/header&gt;
'''
    return outstring


</t>
<t tx="leo.20181104192502.55">def set_footer():
    """footer for page"""
    return "&lt;footer&gt; \
        &lt;a href='/edit_page'&gt;Edit All&lt;/a&gt;| \
        &lt;a href='" + str(request.url) + "/1'&gt;Edit&lt;/a&gt;| \
        &lt;a href='edit_config'&gt;Config&lt;/a&gt; \
        &lt;a href='login'&gt;login&lt;/a&gt;| \
        &lt;a href='logout'&gt;logout&lt;/a&gt; \
        &lt;br /&gt;Powered by &lt;a href='http://cmsimple.cycu.org'&gt;CMSimply&lt;/a&gt; \
        &lt;/footer&gt; \
        &lt;/body&gt;&lt;/html&gt;"
</t>
<t tx="leo.20181104192502.56">@app.route('/sitemap', defaults={'edit': 1})
@app.route('/sitemap/&lt;path:edit&gt;')
def sitemap(edit):
    """sitemap for dynamic site"""
    head, level, page = parse_content()
    directory = render_menu(head, level, page)
    sitemap = render_menu(head, level, page, sitemap=1)
    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + directory + \
             "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Site Map&lt;/h1&gt;" + sitemap + \
             "&lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"
</t>
<t tx="leo.20181104192502.57">def sitemap2(head):
    """sitemap for static content generation"""
    edit = 0
    not_used_head, level, page = parse_content()
    directory = render_menu2(head, level, page)
    sitemap = render_menu2(head, level, page, sitemap=1)
    return set_css2() + "&lt;div class='container'&gt;&lt;nav&gt;" + directory + \
             "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Site Map&lt;/h1&gt;" + sitemap + \
             "&lt;/section&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.58">def sizeof_fmt(num):
    """size formate"""
    for x in ['bytes','KB','MB','GB']:
        if num &lt; 1024.0:
            return "%3.1f%s" % (num, x)
        num /= 1024.0
    return "%3.1f%s" % (num, 'TB')
</t>
<t tx="leo.20181104192502.59">@app.route('/ssavePage', methods=['POST'])
def ssavePage():
    """seperate save page function"""
    page_content = request.form['page_content']
    page_order = request.form['page_order']
    if not isAdmin():
        return redirect("/login")
    if page_content is None:
        return error_log("no content to save!")
    # 請注意, 若啟用 fullpage plugin 這裡的 page_content tinymce4 會自動加上 html 頭尾標註
    page_content = page_content.replace("\n","")
    head, level, page = parse_content()
    original_head_title = head[int(page_order)]
    # 在插入新頁面資料前, 先複製 content.htm 一分到 content_backup.htm
    shutil.copy2(config_dir + "content.htm", config_dir + "content_backup.htm")
    file = open(config_dir + "content.htm", "w", encoding="utf-8")
    for index in range(len(head)):
        if index == int(page_order):
            file.write(page_content)
        else:
            file.write("&lt;h"+str(level[index])+ "&gt;" + str(head[index]) + "&lt;/h" + \
                          str(level[index])+"&gt;"+str(page[index]))
    file.close()
    # if every ssavePage generate_pages needed
    #generate_pages()

    # if head[int(page_order)] still existed and equal original_head_title, go back to origin edit status, otherwise go to "/"
    # here the content is modified, we need to parse the new page_content again
    head, level, page = parse_content()
    # for debug
    # print(original_head_title, head[int(page_order)])
    # 嘗試避免因最後一個標題刪除儲存後產生 internal error 問題
    if original_head_title is None:
        return redirect("/")
    if original_head_title == head[int(page_order)]:
        #edit_url = "/get_page/" + urllib.parse.quote_plus(head[int(page_order)]) + "&amp;edit=1"
        #edit_url = "/get_page/" + urllib.parse.quote_plus(original_head_title) + "/1"
        edit_url = "/get_page/" + original_head_title + "/1"
        return redirect(edit_url)
    else:
        return redirect("/")


</t>
<t tx="leo.20181104192502.6">@app.route('/download/', methods=['GET'])
def download():
    """Download file using URL."""
    filename = request.args.get('filename')
    type = request.args.get('type')
    if type == "files":
        return send_from_directory(download_dir, filename=filename)
    else:
    # for image files
        return send_from_directory(image_dir, filename=filename)
    

</t>
<t tx="leo.20181104192502.60">def syntaxhighlight():
    return '''
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shCore.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushJScript.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushJava.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushPython.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushSql.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushXml.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushPhp.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushLua.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushCpp.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushCss.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/syntaxhighlighter/shBrushCSharp.js"&gt;&lt;/script&gt;
&lt;link type="text/css" rel="stylesheet" href="/static/syntaxhighlighter/css/shCoreDefault.css"/&gt;
&lt;script type="text/javascript"&gt;SyntaxHighlighter.all();&lt;/script&gt;

&lt;!-- for LaTeX equations 暫時不用
    &lt;script src="https://scrum-3.github.io/web/math/MathJax.js?config=TeX-MML-AM_CHTML" type="text/javascript"&gt;&lt;/script&gt;
    &lt;script type="text/javascript"&gt;
    init_mathjax = function() {
        if (window.MathJax) {
            // MathJax loaded
            MathJax.Hub.Config({
                tex2jax: {
                    inlineMath: [ ['$','$'], ["\\\\(","\\\\)"] ],
                    displayMath: [ ['$$','$$'], ["\\\\[","\\\\]"] ]
                },
                displayAlign: 'left', // Change this to 'center' to center equations.
                "HTML-CSS": {
                    styles: {'.MathJax_Display': {"margin": 0}}
                }
            });
            MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
        }
    }
    init_mathjax();
    &lt;/script&gt;
 --&gt;
 &lt;!-- 暫時不用
&lt;script src="/static/fengari-web.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/Cango-13v08-min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/CangoAxes-4v01-min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="/static/gearUtils-05.js"&gt;&lt;/script&gt;
--&gt;
&lt;!-- for Brython 暫時不用
&lt;script src="https://scrum-3.github.io/web/brython/brython.js"&gt;&lt;/script&gt;
&lt;script src="https://scrum-3.github.io/web/brython/brython_stdlib.js"&gt;&lt;/script&gt;
--&gt;
'''



</t>
<t tx="leo.20181104192502.61">def syntaxhighlight2():
    return '''
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shCore.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushJScript.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushJava.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushPython.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushSql.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushXml.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushPhp.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushLua.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushCpp.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushCss.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/syntaxhighlighter/shBrushCSharp.js"&gt;&lt;/script&gt;
&lt;link type="text/css" rel="stylesheet" href="./../static/syntaxhighlighter/css/shCoreDefault.css"/&gt;
&lt;script type="text/javascript"&gt;SyntaxHighlighter.all();&lt;/script&gt;

&lt;!-- for LaTeX equations 暫時不用
&lt;script src="https://scrum-3.github.io/web/math/MathJax.js?config=TeX-MML-AM_CHTML" type="text/javascript"&gt;&lt;/script&gt;
&lt;script type="text/javascript"&gt;
init_mathjax = function() {
    if (window.MathJax) {
        // MathJax loaded
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [ ['$','$'], ["\\\\(","\\\\)"] ],
                displayMath: [ ['$$','$$'], ["\\\\[","\\\\]"] ]
            },
            displayAlign: 'left', // Change this to 'center' to center equations.
            "HTML-CSS": {
                styles: {'.MathJax_Display': {"margin": 0}}
            }
        });
        MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
    }
}
init_mathjax();
&lt;/script&gt;
--&gt;
&lt;!-- 暫時不用
&lt;script src="./../static/fengari-web.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/Cango-13v08-min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/CangoAxes-4v01-min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="./../static/gearUtils-05.js"&gt;&lt;/script&gt;
--&gt;
&lt;!-- for Brython 暫時不用
&lt;script src="https://scrum-3.github.io/web/brython/brython.js"&gt;&lt;/script&gt;
&lt;script src="https://scrum-3.github.io/web/brython/brython_stdlib.js"&gt;&lt;/script&gt;
--&gt;
'''


</t>
<t tx="leo.20181104192502.62">def tinymce_editor(menu_input=None, editor_content=None, page_order=None):
    sitecontent =file_get_contents(config_dir + "content.htm")
    editor = set_admin_css() + editorhead() + '''&lt;/head&gt;''' + editorfoot()
    # edit all pages
    if page_order is None:
        outstring = editor + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                        menu_input + "&lt;/nav&gt;&lt;section&gt;&lt;form method='post' action='savePage'&gt; \
                        &lt;textarea class='simply-editor' name='page_content' cols='50' rows='15'&gt;" +  \
                        editor_content + "&lt;/textarea&gt;&lt;input type='submit' value='save'&gt; \
                        &lt;/form&gt;&lt;/section&gt;&lt;/body&gt;&lt;/html&gt;"
    else:
        # add viewpage button wilie single page editing
        head, level, page = parse_content()
        outstring = editor + "&lt;div class='container'&gt;&lt;nav&gt;" + \
                        menu_input+"&lt;/nav&gt;&lt;section&gt;&lt;form method='post' action='/ssavePage'&gt; \
                        &lt;textarea class='simply-editor' name='page_content' cols='50' rows='15'&gt;" + \
                        editor_content + "&lt;/textarea&gt;&lt;input type='hidden' name='page_order' value='" + \
                        str(page_order) + "'&gt;&lt;input type='submit' value='save'&gt;"
        outstring += '''&lt;input type=button onClick="location.href='/get_page/''' + \
                    head[page_order] + \
                    ''''" value='viewpage'&gt;&lt;/form&gt;&lt;/section&gt;&lt;/body&gt;&lt;/html&gt;'''
    return outstring


</t>
<t tx="leo.20181104192502.63">def unique(items):
    """make items element unique"""
    found = set([])
    keep = []
    count = {}
    for item in items:
        if item not in found:
            count[item] = 0
            found.add(item)
            keep.append(item)
        else:
            count[item] += 1
            keep.append(str(item) + "_" + str(count[item]))
    return keep


</t>
<t tx="leo.20181104192502.7">@app.route('/download_list', methods=['GET'])
def download_list():
    """List files in downloads directory."""
    if not isAdmin():
        return redirect("/login")
    else:
        if not request.args.get('edit'):
            edit= 1
        else:
            edit = request.args.get('edit')
        if not request.args.get('page'):
            page = 1
        else:
            page = request.args.get('page')
        if not request.args.get('item_per_page'):
            item_per_page = 10
        else:
            item_per_page = request.args.get('item_per_page')
        if not request.args.get('keyword'):
            keyword = ""
        else:
            keyword = request.args.get('keyword')
            session['download_keyword'] = keyword
    files = os.listdir(download_dir)
    if keyword is not "":
        files = [elem for elem in files if str(keyword) in elem]
    files.sort()
    total_rows = len(files)
    totalpage = math.ceil(total_rows/int(item_per_page))
    starti = int(item_per_page) * (int(page) - 1) + 1
    endi = starti + int(item_per_page) - 1
    outstring = "&lt;form method='post' action='delete_file'&gt;"
    notlast = False
    if total_rows &gt; 0:
        outstring += "&lt;br /&gt;"
        if (int(page) * int(item_per_page)) &lt; total_rows:
            notlast = True
        if int(page) &gt; 1:
            outstring += "&lt;a href='"
            outstring += "download_list?&amp;amp;page=1&amp;amp;item_per_page=" + str(item_per_page) + \
                                "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;&lt;&lt;&lt;/a&gt; "
            page_num = int(page) - 1
            outstring += "&lt;a href='"
            outstring += "download_list?&amp;amp;page=" + str(page_num) + "&amp;amp;item_per_page=" + \
                                str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;Previous&lt;/a&gt; "

        span = 10

        for index in range(int(page)-span, int(page)+span):
            if index&gt;= 0 and index&lt; totalpage:
                page_now = index + 1 
                if page_now == int(page):
                    outstring += "&lt;font size='+1' color='red'&gt;" + str(page) + " &lt;/font&gt;"
                else:
                    outstring += "&lt;a href='"
                    outstring += "download_list?&amp;amp;page=" + str(page_now) + "&amp;amp;item_per_page=" + \
                                        str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
                    outstring += "'&gt;"+str(page_now) + "&lt;/a&gt; "

        if notlast == True:
            nextpage = int(page) + 1
            outstring += " &lt;a href='"
            outstring += "download_list?&amp;amp;page=" + str(nextpage) + "&amp;amp;item_per_page=" + \
                                str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;Next&lt;/a&gt;"
            outstring += " &lt;a href='"
            outstring += "download_list?&amp;amp;page=" + str(totalpage) + "&amp;amp;item_per_page=" + \
                                str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;&gt;&gt;&lt;/a&gt;&lt;br /&gt;&lt;br /&gt;"

        if (int(page) * int(item_per_page)) &lt; total_rows:
            notlast = True
            outstring += downloadlist_access_list(files, starti, endi) + "&lt;br /&gt;"
        else:
            outstring += "&lt;br /&gt;&lt;br /&gt;"
            outstring += downloadlist_access_list(files, starti, total_rows) + "&lt;br /&gt;"

        if int(page) &gt; 1:
            outstring += "&lt;a href='"
            outstring += "download_list?&amp;amp;page=1&amp;amp;item_per_page=" + str(item_per_page) + \
                                "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;&lt;&lt;&lt;/a&gt; "
            page_num = int(page) - 1
            outstring += "&lt;a href='"
            outstring += "download_list?&amp;amp;page=" + str(page_num) + "&amp;amp;item_per_page=" + \
                                str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;Previous&lt;/a&gt; "

        span = 10

        for index in range(int(page)-span, int(page)+span):
        #for ($j=$page-$range;$j&lt;$page+$range;$j++)
            if index &gt;=0 and index &lt; totalpage:
                page_now = index + 1
                if page_now == int(page):
                    outstring += "&lt;font size='+1' color='red'&gt;" + str(page)+" &lt;/font&gt;"
                else:
                    outstring += "&lt;a href='"
                    outstring += "download_list?&amp;amp;page=" + str(page_now) + \
                                        "&amp;amp;item_per_page=" + str(item_per_page) + \
                                        "&amp;amp;keyword=" + str(session.get('download_keyword'))
                    outstring += "'&gt;" + str(page_now)+"&lt;/a&gt; "

        if notlast == True:
            nextpage = int(page) + 1
            outstring += " &lt;a href='"
            outstring += "download_list?&amp;amp;page=" + str(nextpage) + "&amp;amp;item_per_page=" + \
                                str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;Next&lt;/a&gt;"
            outstring += " &lt;a href='"
            outstring += "download_list?&amp;amp;page=" + str(totalpage) + "&amp;amp;item_per_page=" + \
                                str(item_per_page) + "&amp;amp;keyword=" + str(session.get('download_keyword'))
            outstring += "'&gt;&gt;&gt;&lt;/a&gt;"
    else:
        outstring += "no data!"
    outstring += "&lt;br /&gt;&lt;br /&gt;&lt;input type='submit' value='delete'&gt;&lt;input type='reset' value='reset'&gt;&lt;/form&gt;"

    head, level, page = parse_content()
    directory = render_menu(head, level, page)

    return set_css() + "&lt;div class='container'&gt;&lt;nav&gt;" + \
               directory + "&lt;/nav&gt;&lt;section&gt;&lt;h1&gt;Download List&lt;/h1&gt;" + outstring + "&lt;br/&gt;&lt;br /&gt;&lt;/body&gt;&lt;/html&gt;"


</t>
<t tx="leo.20181104192502.8">def downloadlist_access_list(files, starti, endi):
    """List files function for download_list."""
    # different extension files, associated links were provided
    # popup window to view images, video or STL files, other files can be downloaded directly
    # files are all the data to list, from starti to endi
    # add file size
    outstring = ""
    for index in range(int(starti)-1, int(endi)):
        fileName, fileExtension = os.path.splitext(files[index])
        fileExtension = fileExtension.lower()
        fileSize = sizeof_fmt(os.path.getsize(download_dir+"/"+files[index]))
        # images files
        if fileExtension == ".png" or fileExtension == ".jpg" or fileExtension == ".gif":
            outstring += '&lt;input type="checkbox" name="filename" value="' + \
                              files[index] + '"&gt;&lt;a href="javascript:;" onClick="window.open(\'/images/'+ \
                              files[index] + '\',\'images\', \'catalogmode\',\'scrollbars\')"&gt;' + \
                              files[index] + '&lt;/a&gt; (' + str(fileSize) + ')&lt;br /&gt;'
        # stl files
        elif fileExtension == ".stl":
            outstring += '&lt;input type="checkbox" name="filename" value="' + \
                              files[index] + '"&gt;&lt;a href="javascript:;" onClick="window.open(\'/static/viewstl.html?src=/downloads/' + \
                              files[index] + '\',\'images\', \'catalogmode\',\'scrollbars\')"&gt;' + \
                              files[index] + '&lt;/a&gt; (' + str(fileSize) + ')&lt;br /&gt;'
        # flv files
        elif fileExtension == ".flv":
            outstring += '&lt;input type="checkbox" name="filename" value="' + \
                              files[index] + '"&gt;&lt;a href="javascript:;" onClick="window.open(\'/flvplayer?filepath=/downloads/' + \
            files[index] + '\',\'images\', \'catalogmode\',\'scrollbars\')"&gt;' + files[index] + '&lt;/a&gt; (' + str(fileSize) + ')&lt;br /&gt;'
        # direct download files
        else:
            outstring += "&lt;input type='checkbox' name='filename' value='" + files[index] + \
                              "'&gt;&lt;a href='/downloads/" + files[index] + "'&gt;" + files[index] + \
                              "&lt;/a&gt; (" + str(fileSize) + ")&lt;br /&gt;"
    return outstring


# downloads 方法主要將位於 downloads 目錄下的檔案送回瀏覽器
</t>
<t tx="leo.20181104192502.9">@app.route('/downloads/&lt;path:path&gt;')
def downloads(path):
    """Send files in downloads directory."""
    return send_from_directory(_curdir+"/downloads/", path)


# 與 file_selector 搭配的取檔程式
</t>
</tnodes>
</leo_file>
